### ISSUE TITLE
Onkyo TX-8050: Device failed to play

### ISSUE THREAD

**Issue by jlehtnie** [masmu/pulseaudio-dlna#133]
Streaming from pulseaudio-dlna to TX-8050 fails. Play fails with error code 716: Resource not found. Debug log attached.

[Onkyo-tx-8050.txt](https://github.com/masmu/pulseaudio-dlna/files/48999/Onkyo-tx-8050.txt)

**Comment by masmu** [comment]
Hmm, I looked into your _debug.log_ and there is one odd thing. Your device seems to start streaming just after registering the url which to play. Normally it should wait until it gets instructed to start playing. This is a 2 step process. Set the url and instruct it to play what was set. But yours seem to start right after setting. 
Could you give me a second _debug.log_ so that I can compare it with the first one?

**Comment by jlehtnie** [comment]
Yes. I can confirm that this happens everytime: GET request to the stream URL is always received from the device before pulseaudio-dlna sends the PLAY command. Another debug log attached.

[Onkyo-tx-8050.2.txt](https://github.com/masmu/pulseaudio-dlna/files/51197/Onkyo-tx-8050.2.txt)

**Comment by masmu** [comment]
Well... there are several things we can try...
- Use the `--disable-switchback` flag. Normally if something fails during the 2 step _play_ process the stream gets switched back to the original sink. That flag suppresses that behaviour. So, I would expect that there are still errors in the log, but the device could start to play.

- Find the `upnp/renderer.py` line 380 and change it to the following:
```python
class CoinedUpnpMediaRenderer(
        pulseaudio_dlna.plugins.renderer.CoinedBaseRendererMixin, UpnpMediaRenderer):

    def play(self, url=None, codec=None, artist=None, title=None, thumb=None):
        try:
            stream_url = url or self.get_stream_url()
            return_code = UpnpMediaRenderer.register(
                self, stream_url, codec,
                artist=artist, title=title, thumb=thumb)
            return return_code
        except requests.exceptions.ConnectionError:
            logger.error('The device refused the connection!')
            return 404
        except pulseaudio_dlna.plugins.renderer.NoSuitableEncoderFoundException:
            logger.error('Could not find a suitable encoder!')
            return 500
```
(The original code shows the 2 step process, for testing purposes we leave the _play_ action out.)

- Search the settings of your device for something like _automatic start to play_ or stuff like that. I had a bunch of devices here, this one is the first which behaves like that.

**Comment by jlehtnie** [comment]
Thank you very much for your help! I was trying the things you suggested. I did not get it working yet, but I have got much more information.

First of all using ```--disable-switchback``` flag did not seem to make any difference. But when I disabled the play action in the source code as you suggested, I did not receive http get for the stream at all anymore. Thus it seems that sending the register url does **not** trigger the streaming after all.

Then I was adding some more detailed logging to ```UpnpMediaRenderer.play()```  and took Wireshark capture[1] of the communication. I learned that the device does not send any kind of reply to the play request! Or should I say that it replies immediately with get stream request. On the pulseaudio-dlna the play-request is pending for response but meanwhile the device is waiting for the stream download to start. Thus they are waiting for each other until after 5 seconds the device sends HTTP 500 (716: resource not found). This is probably some sort of timeout for the stream download.

I also tried setting the play request timeout to one millisecond and ignoring the timeout exception. But it still seems that starting up the stream takes longer than the device is willing to wait. I will continue to debug this. Naturally any ideas how to continue are warmly welcome!

[1] https://jil.kapsi.fi/onkyo-tx8050-capture.pcapng

**Comment by masmu** [comment]
I am getting the feeling that your device works correct. In your capture you can see that your computer accepts the request and receives the GET header but never sends data back to the device. I studies the code of the `streamserver.py` again and I recognized that there is an important log missing. `Starting processes "{recorder} | {encoder}"` (line 305) So, I am pretty sure that is why no data was sent. For some reason the encoder was not launched... So, I would focus on that module. The method which is called on every GET request is: 
```python
StreamRequestHandler.do_GET(self) # line 423
```
Find out why line 423 never reaches line 305.

Btw, excellent wireshark capture!

**Comment by jlehtnie** [comment]
Thanks for the hints again. There must have been some another issue in the previous debug log too because I will get your mentioned ```Starting processes ...``` trace now. But I also noticed that there are very suspicious traces like this:

```INFO     Could not get socket IP and Port. Setting to unknown.```

And it seems that in the ```streamserver.communicate()``` ```socket.send_data()``` fails because the client address has not been set for some reason. I will attach the new debug log.

[Onkyo-tx-8050.3.txt](https://github.com/masmu/pulseaudio-dlna/files/52915/Onkyo-tx-8050.3.txt)

**Comment by masmu** [comment]
Hmm, something is taking really long. See here:
```
12-05 17:42:28 pulseaudio_dlna.streamserver                   DEBUG    Got the following GET request
12-05 17:42:33 pulseaudio_dlna.streamserver                   DEBUG    Starting processes "parec --format=s16le -d tx8050_dlna.monitor | lame -b 192 -r -"
```

We receive the request at 17:42:28 but the encoder is started at 17:42:33. In those 5 seconds there is no data sent throught the socket which i assume makes the device disconnect.
```
12-05 17:42:33 pulseaudio_dlna.streamserver                   INFO     Client unknown unregistered stream /dWRuPSJ1dWlkOjcyMGZhZTlhLTE3YmQtNDliMi04ODEwLTJlNTg0NmZjODM5YyIsdHlwZT0iYnJpZGdlIg%3D%3D/stream.mp3 using method 2.
```
(method 2 happens when the device closed the connection from its end)
And i guess your hint about the error could be an explanation for this. Maybe the `peername` detection is taking too long.

Please try to modify the `streamserver.py`'s _RemoteDevice_ class like that:

```python
# line 56
@functools.total_ordering
class RemoteDevice(object):
    def __init__(self, bridge, sock):
        self.bridge = bridge
        self.sock = sock
        try:
            self.ip, self.port = ('foo', 'bar')
        except:
            logger.info('Could not get socket IP and Port. Setting to '
                        'unknown.')
            self.ip = 'unknown'
            self.port = 'unknown'

    def __eq__(self, other):
        if isinstance(other, RemoteDevice):
            return self.ip == other.ip
        raise NotImplementedError

    def __gt__(self, other):
        if isinstance(other, RemoteDevice):
            return self.ip > other.ip
        raise NotImplementedError

    def __str__(self):
        return '<{} socket="{}" ip="{}" port="{}">'.format(
            self.__class__.__name__,
            str(self.sock),
            self.ip,
            self.port,
        )
```
This will break the application for multiple devices, but good enough to see if that is the real problem.

**Comment by jlehtnie** [comment]
I tried your suggested peername hardcoding. I'm not sure if it had any effect at all. I still see this roughly 5 sec delay from the GET request to the streaming start and then the socket disconnects.

However, while playing with this I collected the following traces where the behaviour is otherwise little bit different than before. Namely, we can two stream packets in the capture[1] before the socket disconnects. Also, the device now retries sending the GET request 3 times.

[1] https://jil.kapsi.fi/onkyo-tx8050-capture-peername-foobar.pcapng

[onkyo-tx8050-debug-log-peername-foobar.txt](https://github.com/masmu/pulseaudio-dlna/files/59802/onkyo-tx8050-debug-log-peername-foobar.txt)

**Comment by masmu** [comment]
Any progress here?

**Comment by jlehtniemi-broadsoft** [comment]
No, not really. It has been on-hold on my part. I will try to find some time to continue debugging it soonish.

**Comment by memfail** [comment]
I have the same problem using an Onkyo TX-609. 
When I try to connect to my Panasonic-TV Pulseaudio works great.

**Comment by shiznix** [comment]
Me too, same problem using an Onkyo TX-NR616.
Audio plays for roughly 5 seconds then immediately disconnects with the connection timeout "failed to play! (408)" in pulseaudio-dlna.

Have to keep turning the Samsung TV on and streaming pulseaudio-dlna through that.

**Comment by masmu** [comment]
I may have found the issue. For the _Samsung_ devices and for the _Onkyo_ ones. Please try out [that branch](https://github.com/masmu/pulseaudio-dlna/tree/feature/ffmpeg-backend). You need to install _ffmpeg_ or _avconv_ for this.

**Comment by shiznix** [comment]
Testing the new ffmpeg branch doesn't fix the Onkyo problem and now breaks ability to stream to Samsung TV.

I have attached debug logs using the new branch for both attempts to play through Onkyo AVR and Sumsung TV.

Thanks.

[SamsungTV_ffmpeg-backend.log.txt](https://github.com/masmu/pulseaudio-dlna/files/125548/SamsungTV_ffmpeg-backend.log.txt)
[OnkyoTX-NR616_ffmpeg-backend.log.txt](https://github.com/masmu/pulseaudio-dlna/files/125547/OnkyoTX-NR616_ffmpeg-backend.log.txt)

**Comment by masmu** [comment]
Did you updated the branch?

**Comment by masmu** [comment]
The Onkyo device failed because of a HTTP timeout. This is weird, because there was a successful request to the same URL before.

Have you tried other encoders?

**Comment by shiznix** [comment]
Yes, the lame encoder method as currently used in master branch works fine with the Samsung TV.

So to summarise....
Master Branch (lame):
* Samsung TV - works!
* Onkyo - fails!

FFmpeg feature branch:
* Samsung TV - fails!
* Onkyo - fails!

**Comment by shiznix** [comment]
Well here's some positive news.
All streaming works (both OnkyoAVR and SamsungTV) if I roll back to version 0.4.4
Onkyo streaming breaks as of the 0.4.5 release.

So there seems to be an errant commit between the 0.4.4 and 0.4.5 releases.

**Comment by masmu** [comment]
Samsung:
Whats about other _ffmpeg_ codecs besides _mp3_ for the Samsung TV?

Just to make sure is really the encoder (_lame_ / _ffmpeg_) alone and no other change I created a [branch](https://github.com/masmu/pulseaudio-dlna/tree/testing/samsung-tv) where I reverted back to _lame_. Please check that out.

Onkyo:
Good job identifying the breaking commit. Since there are not that many changes, may I ask you to revert the changes step by step to identify the exact problem?

**Comment by masmu** [comment]
What you could try first is a [that new branch](https://github.com/masmu/pulseaudio-dlna/tree/refactor/separate-encoder-streams). It just uses _ffmpeg_ but code complexity was minimized a lot and I am pretty sure there are no dead locks in it. E.g. all the _threading changes_ stuff was wiped from this.

**Comment by jlehtniemi-broadsoft** [comment]
I tested the ffmpeg branch with Onkyo TX-8050 but no luck.

Wireshark capture: https://jil.kapsi.fi/onkyo-tx8050-ffmpeg-backend.pcapng
Debug log: [onkyo-tx8050-ffmpeg-backend.txt](https://github.com/masmu/pulseaudio-dlna/files/127045/onkyo-tx8050-ffmpeg-backend.txt)

I also tested the old version 0.4.4 as suggested @shiznix but it seems to make no difference with my equipment.

**Comment by jlehtnie** [comment]
I tested the ffmpeg branch with Onkyo TX-8050 but no luck.

Wireshark capture: https://jil.kapsi.fi/onkyo-tx8050-ffmpeg-backend.pcapng
Debug log: [onkyo-tx8050-ffmpeg-backend.txt](https://github.com/masmu/pulseaudio-dlna/files/127045/onkyo-tx8050-ffmpeg-backend.txt)

I also tested the old version 0.4.4 as suggested @shiznix but it seems to make no difference with my equipment.

**Comment by masmu** [comment]
Thanks, could you please also test the refactor branch I suggested to test first?

**Comment by shiznix** [comment]
I've tested both branches, here are the results:
** refactor/separate-encoder-streams **
SamsungTV - fails with unsupported file format message on TV
OnkyoAVR - strange behaviour. Onkyo fails with the usual 408, but if I retry immediately after the failure then it succeeds in playing but with some python errrors.
Debug log attached was created by pasting terminal output as 'pulseaudio-dlna --debug' output seems to strip stderr so python errors are lost.

[OnkyoTX-NR616+refactor_separate-encoder-streams.log.txt](https://github.com/masmu/pulseaudio-dlna/files/127333/OnkyoTX-NR616.refactor_separate-encoder-streams.log.txt)

** testing/samsung-tv **
SamsungTV - works
OnkyoAVR - fails with same 408 error as before

I did try and revert the changes in the breaking commit 314996fa6564fa4c58fdce3a0e95418a8fd40a72 but there were a few lines referenced in the commit that have since changed leading up to current master branch so it couldn't be done cleanly.
I just left these lines and continued forward reverting what lines I could but the runtime test result was still failing.
The last commit where streaming works for both Onkyo and Samsung is commit e556a5e97eb08fcc9e1830d9c0e35eb9ee1a91be on Sep 04.

**Comment by shiznix** [comment]
@jlehtnie You might succeed in testing with other lower versions.
0.4.4 worked for me but my error is a '408' timeout whereas yours is a '716' resource not found.

**Comment by masmu** [comment]
@jlehtnie

Error 716 means that there was something wrong with either the provided stream url or the provided metadata, despite your device tries to play the stream.
In your logs there is still a 5 seconds delay between recieving the request and the start of the encoder. In that time the device will not recieve any data and I **guess** that it therefore complains about not finding a valid ressource. There might be an issue with my implementation of the streamserver, especially because of the `Could not get socket IP and Port. Setting to unknown.` log. Thats why I created a much more simplified version of it in the [refactor/separate-encoder-streams](https://github.com/masmu/pulseaudio-dlna/tree/refactor/separate-encoder-streams) branch.

I googled a bit around and there are plenty of complains that Onkyo recievers fail with that error. The most often suggestions are:

- If the device is not connected via ethernet, especially with a Onkyo Wifi USB stick the device has networking issues.

- Newest firmware?

Furthermore if you own an Android phone, could you test if BubbleUPnP (maybe also availible for iPhone) is able to stream to the device? In case it is a dump would be very helpful.

Could you also try other codecs? Especially _wav_ and _flac_.

**Comment by masmu** [comment]
@shiznix 

I fixed the errors in the branch.

Instructing a DLNA device normally consists of 2 steps:
- Sending a command to register the stream url (basically setting the playlist)
- Sending a command to play (the first item in the playlist)

Most of my devices (and due to the reports I've gotten) most other devices require both steps. But the Onkyo devices (Onkyo TX-NR616 and Onkyo TX-8050) launched their requests directly after the registering command. Thats why I inserted a polling request to check the devices state (`get_protocol_state`) and see if it is necessary to actually send the _play_ command.
That works great in my tests.
The python exception occured right after the _register_ command, during polling the devices state and therefore prevented the _play_ command from being sent. I guess that was the case where your device started to play.
But _pulseaudio-dlna_'s internal state for the device remained _idle_ (not _playing_) and after receiving a signal about a _pulseaudio_ stream change _pulseaudio-dlna_ tried to instruct the device to play again.

The real problem with your device is, that there are those time out errors.
I've seen _play_ and _get_protocol_state_ requests in your logs which sometimes work and which sometimes fail. This is really odd, since those are always the same requests. I could understand if they would always fail, but there seems to be no other explanation than network issues or device failure to me. I've experience such a behaviour with some devices sitting behind an unreliable wifi extender.

How is the device connected? Ethernet? USB-Wifi-Stick?
Is the device running the latest firmware?

I remember a guy with an Onkyo reciever asking for adding the `--request-timeout` flag ([Issue 102](https://github.com/masmu/pulseaudio-dlna/issues/102)) stating out his reciever is kind of slow.
And right after the the breaking commit there is the commit [314996f](https://github.com/masmu/pulseaudio-dlna/commit/314996fa6564fa4c58fdce3a0e95418a8fd40a72) which inserts requests timeouts.
I am getting the feeling that yours might be too. So, lets try starting _pulseaudio-dlna_ with the `--request-timeout` option. Try setting it to _30_ or more seconds.

So, what we know:
- The Onkyo TX-NR616 is potentially able to work with _ffmpeg_'s mp3 streams.
- The device starts the request **before** actually sending the _play_ command. So, there might be an auto play feature which may be turned of in the device's settings.

**Comment by jlehtnie** [comment]
Thanks for all the new suggestions!

* I found _Auto-play_ setting for TX-8050 but disabling it did not seem to make much difference. Anyhow it has now been disabled.
* I tested the branch [refactor/separate-encoder-streams](https://github.com/masmu/pulseaudio-dlna/tree/refactor/separate-encoder-streams). I did not observe any difference but here are the [log](https://jil.kapsi.fi/onkyo-tx8050-refactor-separate-encoder-streams_no-auto-play.txt) and [capture](https://jil.kapsi.fi/onkyo-tx8050-refactor-separate-encoder-streams_no-auto-play.pcapng) anyway
* I tested the same branch with _wav_ and _flac_ encoders. Same behaviour with _wav_ ([log](https://jil.kapsi.fi/onkyo-tx8050-refactor-separate-encoder-streams_no-auto-play_encoder-wav.txt) & [capture](https://jil.kapsi.fi/onkyo-tx8050-refactor-separate-encoder-streams_no-auto-play_encoder-wav.pcapng)), for _flac_ it pulseaudio-dlna says that it is not supported ([log](https://jil.kapsi.fi/onkyo-tx8050-refactor-separate-encoder-streams_no-auto-play_encoder-flac.txt) and [capture](https://jil.kapsi.fi/onkyo-tx8050-refactor-separate-encoder-streams_no-auto-play_encoder-flac.pcapng)).
* I did test BubbleUPnP and it works and here is the [capture](https://jil.kapsi.fi/onkyo-tx8050-and-bubbleupnp.pcap)
* TX-8050 is connected to Ethernet and the firmware should be up-to-date

**Comment by shiznix** [comment]
Brilliant! '--request-timeout' was the magic I needed.

Back on 'master' branch and can confirm that running 'pulseaudio-dlna' still causes 408 connection errors with Onkyo.
But running as low as 'pulseaudio-dlna --request-timeout=15' reliably connects with no error.

Onkyo is connected to network via ethernet.
Thanks for your patience and a solution @masmu :)

**Comment by masmu** [comment]
@jlehtnie Sorry for the delay.

I am still focused on the 5 second delay in your logs. Therefore I created a branch [testing/onkyo-tx-8050](https://github.com/masmu/pulseaudio-dlna/tree/testing/onkyo-tx-8050) which logs exactly what when happens.

Could you try it out? Hopefully we find what is taking those 5 seconds...

**Comment by jlehtnie** [comment]
No problem @masmu, here are some logs using that branch and a couple of different codecs. 

[onkyo-tx8050-testing-enc-wav.txt](https://github.com/masmu/pulseaudio-dlna/files/145244/onkyo-tx8050-testing-enc-wav.txt)
[onkyo-tx8050-testing-enc-mp3.txt](https://github.com/masmu/pulseaudio-dlna/files/145247/onkyo-tx8050-testing-enc-mp3.txt)
[onkyo-tx8050-testing-enc-l16.txt](https://github.com/masmu/pulseaudio-dlna/files/145248/onkyo-tx8050-testing-enc-l16.txt)

**Comment by masmu** [comment]
@jlehtnie I've disabled the line which took 5 seconds and updated the branch. Could you please retry?

**Comment by jlehtnie** [comment]
Yes! I confirm that it works now, well done @masmu.
Thank you very much!

**Comment by masmu** [comment]
@jlehtnie You are welcome. It was the logging line in
```python
    def log_message(self, format, *args):
        args = [unicode(arg) for arg in args]
        logger.info('Got request from {host} - {args}' .format(
            host=self.address_string(),
            time=self.log_date_time_string(),
            args=','.join(args)))
```
I guess it is the `self.address_string()` call. This could be a network configuration issue on your side.
Please checkout current master. I removed that log there as well.

**Comment by jlehtnie** [comment]
Also the master works OK now!

This seems to be a known issue with python ``socket.gethostbyaddr()``. I found a lot of cries about similar problems by googling _"python gethostbyaddr timeout"_.

It does not seem to be a network configuration issue. ``host``, ``dig``, and ``nslookup`` manage to resolve the reverse lookup in a snap, e.g.:

    $ time host 192.168.10.41
    Host 41.10.168.192.in-addr.arpa. not found: 3(NXDOMAIN)
    ...
    real	0m0.015s
    ...

But

    $ time python -c 'import socket; socket.gethostbyaddr("192.168.10.41")'
    ...
    socket.herror: [Errno 1] Unknown host
    ...
    real	0m5.072s
    ...

**Comment by masmu** [comment]
Well, there are your 5 seconds :wink: ... pretty exactly. That call was blocking the thread the whole time and the encoder was not started during that. And your device disconnected after a specific period of time not receiving any data.

Could you it a quick test for the devices codecs? Like to add them to the list of supported devices.

**Comment by masmu** [comment]
Maybe a DNS problem?

**Comment by jlehtnie** [comment]
Ok. I have tested the codecs.

codec | status
--------|---------
wav, l16 | streaming ok with good quality
mp3 | streaming but quality is poor, lots of breaks and cuts etc.
flac, ogg, opus, and aac | not supported by the device

About the DNS: yes, you can say that it is a DNS problem in a way. Namely that there is no DNS server for this private IP network. But that is a pretty normal case in a home LAN. To me the real problem is that ``socket.gethostbyaddr()`` uses such an absurdly long default timeout **and** does not even allow user to lower it.

But I guess that bug report should be filed to cpython and not pulseaudio-dlna :)

Thank you once more for solving the issue!

**Comment by masmu** [comment]
Thank you. I am glad that I could help.

Regarding timeouts:
I recently increased the default HTTP request timeout to 15 seconds. At first it was about 5 seconds to also be safe in slow networks. But some manufacturers HTTP server responses are implemented blocking, so that the request idles until the requested information is available. And due to this I had to increase the timeout to an absurd value to make it work. Maybe there is a similar story behind that `gethostbyaddr()` implementation.

In case your device is connected via cable there is no better option than _wav_ and _l16_. If you prefer other codecs for some reason you can try the `--encoder-backend` option. Maybe _ffmpeg_ will do a better job than _lame_.

**Comment by masmu** [comment]
* __0.5.0__ - (_2016-03-09_)
    - Set Yamaha devices to the appropriate mode before playing (thanks to [hlchau](https://github.com/hlchau)) (new dependency: `python-lxml`)
    - Fixed a bug where some SSDP messages could not get parsed correctly
    - Also support media renderers identifying as `urn:schemas-upnp-org:device:MediaRenderer:2`
    - Added the `--disable-workarounds` flag
    - Added the `--auto-reconnect` flag
    - Added the `--encoder-backend` option (new optional dependencies `ffmpeg`, `libav-tools`)
    - Removed shared encoder processes
    - Increased the default HTTP timeout to 15 seconds
    - Fixed a bug where manually added renderers could appear twice
    - Added device state polling for devices which start playing on their own
    - Added the flac encoder for _Google Chromecast_
    - Added support for _Google Cast Groups_ (new dependency `python-zeroconf`)
    - Removed dependency `python-beautifulsoup`
    - Fixed a bug where bytes were not decoded properly to unicode
