### ISSUE TITLE
Stream is distorted when changing volume

### ISSUE THREAD

**Issue by Yannik** [masmu/pulseaudio-dlna#134]
Hi,
thanks for this awesome application!!
Streaming to a Onkyo TX-NR616 works well with `pulseaudio-dlna --encoder wav`. 

However, I experience massive distortion when changing the system volume:
```
12-06 23:04:14 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream567"
12-06 23:04:14 pulseaudio_dlna.pulseaudio                     ERROR    PulseStreamFactory - Could not get "/org/pulseaudio/core1/playback_stream567" from dbus.
12-06 23:04:14 pulseaudio_dlna.pulseaudio                     INFO     on_playback_stream_removed "/org/pulseaudio/core1/playback_stream567"
12-06 23:04:15 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream568"
12-06 23:04:15 pulseaudio_dlna.pulseaudio                     ERROR    PulseStreamFactory - Could not get "/org/pulseaudio/core1/playback_stream568" from dbus.
12-06 23:04:15 pulseaudio_dlna.pulseaudio                     INFO     on_playback_stream_removed "/org/pulseaudio/core1/playback_stream568"
12-06 23:04:15 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream569"
12-06 23:04:15 pulseaudio_dlna.pulseaudio                     ERROR    PulseStreamFactory - Could not get "/org/pulseaudio/core1/playback_stream569" from dbus.
12-06 23:04:15 pulseaudio_dlna.pulseaudio                     INFO     on_playback_stream_removed "/org/pulseaudio/core1/playback_stream569"
12-06 23:04:15 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream570"
12-06 23:04:15 pulseaudio_dlna.pulseaudio                     ERROR    PulseStreamFactory - Could not get "/org/pulseaudio/core1/playback_stream570" from dbus.
12-06 23:04:15 pulseaudio_dlna.pulseaudio                     INFO     on_playback_stream_removed "/org/pulseaudio/core1/playback_stream570"
```

This does not happen when changing the volume on the application level.

I read the known issues:
```
Distorted sound

If you experience distorted sound, try to pause / unpause the playback or changing / adjusting the volume. Some encoders handle volume changes better than others. The lame encoder handles this by far better than most of the other ones.
```
Is this the same problem that I described? For me, changing to the lame encoder did not improve the distortion.

What is the cause of this? Is there a solution or workaround for fixing it?

**Comment by masmu** [comment]
Those small _ERROR_ message in your log are irrelevant for this problem. Those occur if your system creates a very short sound, like the one if you are miss typing in a terminal. Those sounds are gone before _pulseaudio-dlna_ is able to retrieve them.

> Is this the same problem that I described? For me, changing to the lame encoder did not improve the distortion.

It sounds like it is. I do not suffer from this problem at all. All my devices handle this pretty well, besides a _Sonos_ speaker I had some time ago. That device made the crackling noise when changing the volume.

I assume, that this problem comes from your device's decoder capabilities in handling volume changes. Normally a audio stream does change its audio level within a specific range. But since you can change this range additionally through _pulseaudio_'s audio controls it can happen that you get under or over this range. Some devices handle this pretty well, some do not. AFAIK, there is no workaround for that but not using _pulseaudio_'s audio controls. In pulseaudio 6.0, _pulseaudio_ won't change your audio levels depending on the selected sink any more, which should help.

**Comment by dandv** [comment]
Duplicate of #198?

**Comment by masmu** [comment]
Jep. But I analyzed that issue more and I guess now it is not the devices decoder, it is the systems encoder which causes the problem. But for the same reason, it is not capable of handling volume changes well.
