### ISSUE TITLE
UnicodeDecodeError when streming to Kodi

### ISSUE THREAD

**Issue by chrodriguez** [masmu/pulseaudio-dlna#136]
When streming audio from my desktop (Ubuntu 14.04) while playing music using Spotify client, I got the following error after some seconds of playing without problems:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 540, in _on_new_message
    getattr(self, message_type)(**message)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 623, in on_bridge_disconnected
    self.switch_back(stopped_bridge, reason)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 590, in switch_back
    self.fallback_sink.label)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)

```

**Comment by masmu** [comment]
Well, could you provide a full _debug.log_?
```bash
pulseaudio-dlna --debug  2>&1 | tee -a debug.log
```

**Comment by masmu** [comment]
Closed due to inactivity.

**Comment by chrodriguez** [comment]
Hi @masmu , sorry for my late response. I've posted the debug log in:

http://pastebin.com/J00jQsk4

Thanks in advance!

**Comment by masmu** [comment]
@chrodriguez I cannot reproduce that error. There is an odd thing with that: The traceback shows that the error occures in `pulseaudio.py`, but it should occure in `utils/encoding.py`.
No idea how that happend.

You can prevent the application getting to that point when using the `--disable-switchback` flag. But in case your stream crashes (because of e.g. weak wifi) your sink does not get switched back.

Are you running _pulseaudio-dlna_ as root?

**Comment by chrodriguez** [comment]
No, I've always run it as my user. Thanks anyway..

**Comment by chrodriguez** [comment]
I've upgraded openelec and kodi to version 15. Now I'm able to play without this error for the last hour without problems!  

thanks!

**Comment by masmu** [comment]
Thanks for mentioning this. You are welcome!
