### ISSUE TITLE
pulseaudio-dlna doesn't respond to M-SEARCH query

### ISSUE THREAD

**Issue by meeuw** [masmu/pulseaudio-dlna#141]
Hi,

I'm trying to use pulseaudio-dlna on my LG HB45 Home Cinema System. It seems to work using bubbleupnp (both the home cinema system and pulseaudio-dlna) but neither the LG HB45 nor pulseaudio-dlna see each other.

The LG HB45 sends the following SSDP packet but this isn't replied by pulseaudio-dlna:
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 7
ST: urn:schemas-upnp-org:device:MediaServer:1

I think it likes to have a response like this:
http://developer.lgappstv.com/TV_HELP/index.jsp?topic=%2Flge.tvsdk.references.book%2Fhtml%2FUDAP%2FUDAP%2FM+SEARCH+Request.htm

**Comment by masmu** [comment]
Yes, that's right. The message emitted by your device is for announcing an media server (DMS), not a media renderer (DMR). There are many devices out there which support both and those emit 2 messages. If your device just announced the one for being a server I guess it does not support rendering functionality. I have met those before.

**Comment by meeuw** [comment]
Thank you for your fast reply! 

I think it is a DMP, from Wikipedia:
Digital Media Player (DMP): find content on digital media servers (DMS) and provide playback and rendering capabilities. Examples include TVs, stereos and home theaters, wireless monitors and game consoles.

Would it be possible to use pulseaudio-dlna as a DMS for a DMP?

**Comment by masmu** [comment]
Well, in context of DLNA there are just 3 roles. The DMS which is basically a file server such as FTP, a DMR which is a device which can be instructed to play a specific resource such as a URL or a file on a DMS and last but no least a DMC. A DMC is just a remote contol and does not play or serve any files. Otherwise there are many devices not just providing one role but two or all three.

pulseaudio-dlna is basically a HTTP streaming server which also understand a specific subset of DLNA headers. But it needs a DMR which can be instructed to play that stream it serves. A DMS won't work because it is just an extended file server but nothing what can play an HTTP stream on its own.

What you always can do is buy a device like the D-Link DCH-M225/E or a Chromecast Audio and connect it via the Aux port to your existing player. Those devices are pure DMRs and with those you can buy the DMR functionality without buying a new player.

**Comment by meeuw** [comment]
Thanks for your explaination! I'm quite sure the LG 45HB has DMR capabilities because it seems to work using bubbleupnp, or isn't that DLNA?

But I'm clueless how DLNA works, wouldn't it be possible to serve the pulseaudio-dlna HTTP streams over DMS which will be consumed by a DMP instead of a DMR?

I'll try to do some reverse engineering of bubbleupnp to see which protocol is used.

**Comment by masmu** [comment]
Yes, but BubbleUPnP is everything. DMS, DMR and DMC. How are you using it? Do you select the LG in BubbleUPnP? Where does the music start to play?

Am 27. Dezember 2015 16:55:48 MEZ, schrieb meeuw <notifications@github.com>:

**Comment by meeuw** [comment]
I select BubbleUPnP on the LG home cinema system, I get a file browser and I can play the media on my phone.

But... I'd like to stream audio from my Linux system to the LG player.

**Comment by masmu** [comment]
Yeah. In that case BubbleUPnP is acting as a DMS and DMR. That's why you can select it in your LG. But pulseaudio-dlna won't show up as that. pulseaudio-dlna will find DMRs and add them as sinks to your system. So, it is essential that your LG supports being a DMR.

**Comment by Cygn** [comment]
Meuw, if I gather correctly what you're trying to do, ie accessing media files on your PC from your LG, pa-dlna isn't the tool you are looking for. You need to install a upnp/dlna media server on your PC. 
It's as easy as activating 'media shares' if you are using gnome 3, or else installing something like rygel, mediatomb or mini-dlna. That will expose the media files on the network so you can access them from your LG, like you do with bubbleUPNP. 

There is also a pulseaudio option (which requires rygel if I gather corretly) in paprefs that goes 'make local devices available as DLNA server' which may make your current audio output show up as a server in your LG.  Didn't test this myself so your mileage may vary.

**Comment by meeuw** [comment]
thanks! I will have a look at rygel!
