### ISSUE TITLE
Config is created empty

### ISSUE THREAD

**Issue by cmaoling** [masmu/pulseaudio-dlna#145]
Hi,
just updated pulseaudio-dlna to 0.4.7.
Unfortunally this made it stop working at all. My config is now empty. :o(
Worked w/ version 0.4.6. fine.
Any suggestions? 
01-04 20:42:32 pulseaudio_dlna.application                    INFO     Using version: 0.4.7
01-04 20:42:32 pulseaudio_dlna.application                    INFO     Using localhost: 192.xxx.xxx.xxx:8080
01-04 20:42:39 pulseaudio_dlna.application                    INFO     Found the following devices:
01-04 20:42:39 pulseaudio_dlna.application                    INFO     Your config was successfully written to "/home/nicolas/.local/share/pulseaudio-dlna/devices.json"

Thanks

**Comment by masmu** [comment]
Well, it should not delete your old config. In case it did, whats about creating a new one?

**Comment by cmaoling** [comment]
I regenerated the config because it is a new version...
So the new one is the empty one.
If I copy-paste the old config back, it is not overwritten but streaming does not work either.
I assumed this empty config is something different compared to the other issues about devices no longer recognized in 0.4.7. 
I was only moving forward from 0.4.6 not 0.3.5...

**Comment by masmu** [comment]
Ok, well i changed the behaviour of the `--create-device-config` flag. In _0.4.7_ there are 2 flags now: `--create-device-config` and `--update-device-config`. It seems that there are no devices found during device discovery. Did you tried it at least 3 times with the `--create-device-config` flag? Sometimes, because of the nature of UDP broadcasts, some devices are missed.

Do you use a firewall / iptables?

Could you paste your old config here? I will take a look at it and see if there this is compatible between those versions.

**Comment by masmu** [comment]
Closed due to inactivity.
