### ISSUE TITLE
"FireTV Stick" Skipping device

### ISSUE THREAD

**Issue by Bastianowicz** [masmu/pulseaudio-dlna#148]
Hi masmu,
pulseaudio-dlna is such a relief. Worked straight out of the box with my Nexus 5. Unfortunately i can't seem to make it work with Amazon Fire TV Stick. It tries to connect with Chromecast plugin and dies with 
```bash
The Chromecast seems not to be an original Chromecast! Model name: "FireTV Stick" Skipping device ...
```
which seems legit since it is indeed not a chromecast. I'd appreciate any help. Thanks

**Comment by masmu** [comment]
Well, it does not die. It is really skipping the device since it is not a Chromecast and does not understand the _castv2_ protocol.

My Research revealed, that for actually controlling the device it requires _python-adb_ which is not available in ubuntu's default repositorys. Besides that, it requires people to enable android debugging in FireTV settings. So it would never work out of the box. For those reasons I never bought that device. It feels like Amazon is not very interested in people using that device with other services than the Amazon ones.

What you can do yourself is installing _Kodi_ on it and enable _DLNA_.

**Comment by klaernie** [comment]
I think the only reason a Fire TV supports the Chromecast API is due to the YouTube app on it - similar to the Spotify Connect client. I think the Chromecast receiver end of the Fire TV is just listing for the AppID of YouTube, all the regular Chromecast senders like my phone and the Chromecast Chrome extension are hardwired to ignore the Fire TV.

**Comment by masmu** [comment]
@klaernie Do they support the Chromecast API? They may broadcast themself via ZeroConf as Chromecast and DLNA devices do. But as far as i know, they did not implement the Chromecast API.

**Comment by Bastianowicz** [comment]
got it to work with kodi indeed. Thank you for your help. It's a little unlucky that firetv put so few afford in these things. But i guess their major target group is not supposed to use it as dlna device.
