### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by klaernie** [masmu/pulseaudio-dlna#172]
Hi @masmu,

would you consider opening PRs for your open branches? It would ease communication a lot, since it is directly linked to the commits they are about. Also problems with the feature in question could be discussed directly on the lines themselves.

Regards,
Andre

**Comment by masmu** [comment]
Are you talking about opening PRs as soon as I pushed them even if they are not finished?

**Comment by klaernie** [comment]
Yes, especially for the unfinished ones. My team at work heavily uses this, as it allows reviews and collaboration before too much work has been done, so the first commits always show general ideas and interfaces, the further ones  implementation and refinement.

**Comment by klaernie** [comment]
In this repo you can publish rough ideas and concepts, and iterate on them, and also get feedback from the users early on

**Comment by masmu** [comment]
Sure, why not. I am not used to this since we are just using it for reviewing branches. But it might be a good idea, especially now that I know I am not the only person who is really observing this repo.

I guess you are asking because of a recent change. What is it? :wink:

**Comment by klaernie** [comment]
Mostly the ffmpeg branch and the misc fixes PRs you created and merged immediately. I don't see the need for PRs like the latter ones, simply because you are the maintainer, so branch merges that don't need community interaction can simply be merged locally (with `git merge --no-ff --log` of cause)

**Comment by klaernie** [comment]
And yeah, *I am watching everything*  ;)

**Comment by masmu** [comment]
I am using that github feature for reviewing it myself. It is like forcing yourself to review it a last time in full concentration mode before merging. Normally somebody else should do the job, but currently this is my best practice.

Whats about the ffmpeg branch and the fixes?

**Comment by klaernie** [comment]
Well, I just noticed that code and comm were a bit more separated that they could be. You are doing really good in maintaining separate branches, but I think opening PRs for RFCs is way better than using issues.

**Comment by masmu** [comment]
You might be right. :wink: Lets do this. I just opened the [google-cast-groups](https://github.com/masmu/pulseaudio-dlna/tree/feature/google-cast-groups) branch, since I already merged the other stuff and there seems to be no immediate need for the recent changes.

I am pretty excited about that branch, because it makes that project for me super useful again. I have to admin, that I was using Android apps recently because those _cast groups_ are just awesome!
But since the alternative cast group port is (imho) just announced via _mdns_ the implementation is not that easy if you don't want to break a few of the features.
