### ISSUE TITLE
Bose SoundTouch 20 fails to register and play

### ISSUE THREAD

**Issue by AdamNo** [masmu/pulseaudio-dlna#211]
Hi,
having trouble making Soundtouch play.
Device discovery works and i can select this Bose device on my Ubuntu 14.04.
But after doing this i can see from log that registration and play fails.

The debug log: 
http://pastebin.com/zMX1zyvq

Thx & Greetings
Adam

**Comment by masmu** [comment]
Did you test your _Bose_ device with another UPNP application like Androids _BubbleUPnP_?

An error during registering normally indicates the following problems:
- Your device is somehow locked and needs to be set in a special mode before you can stream to it. Look in your device manual if that may be necessary. E.g. _Yamaha_ devices need to be set to _SERVER_ mode via remote control before they accept registering.
- The device has a problem with the format of the register XML.

**Comment by AdamNo** [comment]
Hi Masmu,

you pointed me into the right direction.

Since miniDLNA didn't worked either i installed SoundTouch App V13 with Wine on my Ubuntu. I guess this registered my system. In the manual no traces about registration. 

Now everything works just fine apart from one small thing.

Having a VPN tunnel before starting pulseaudio-dlna does not work. 
Opposite, pulseaudio-dlna first, then starting VPN works fine.

I guess your script picks up at start time the tunnel IP? 
Do you have a fix?


Thank you so much for your help.
You are doing a great job!

Greetings
Adam

**Comment by masmu** [comment]
Thanks, glad you figured that out. Do you always need to prepare your device via "SoundTouch App V13" before using the device? Or is this a one time process?

I am not quite sure how the VPN tunnel is related to all this. I guess you are not trying to stream via VPN. It might be that _pulseaudio-dlna_ is detecting the wrong default interface.

Could you get me a full _debug.log_ again for the VPN problem?

**Comment by AdamNo** [comment]
I am quit sure it was a one time registration.
Fortunately, since SoundTouch App Version 13.x forced me to upgrade to V14.x which keeps crashing in Wine. So it works now without this App.

Please have a look at debug.log where I enabled VPN first before I started pulseaudio-dlna. 
I played some music but the Box stays quite. No Sound. Also after I stopped playing music in Clementine the Box display says something like: “Please choose a preset or start playing music using SoundTouch App” (my translation from German).

http://pastebin.com/LHgdb9PC

Greetings
Adam

**Comment by AdamNo** [comment]
ups,

while actually able playing around i just discovered what the Box displays above text every time a stream stops.

Adam

**Comment by masmu** [comment]
Yeah, your device sends all your traffic through `10.56.10.x` and therefore it picks `10.56.10.6` as host address. Two possible workarounds:

- Disable the VPN as default gateway. If you just combined two LANs this is not a problem. Just will be able to reach machines on the otherside and you will benefit from faster traffic using your default internet connection.
But if you are using the VPN for e.g. privacy you should **NOT** do that, because it will route all your traffic using your default internet connection and therefore completely breaking privacy.
- Use the `--host` option, like: `pulseaudio-dlna --host 192.168.0.11` where 192.168.0.11 is the current LAN IP of your machine

I also could implement using the appopriate host address accordingly to the speaker's address.

**Comment by AdamNo** [comment]
I use VPN for a better privacy. I have a quasi fixed IP trough my cable ISP.

Everything works now perfectly!
An “automatic” detection of proper LAN IP would help people (like me) with read weakness when comes to the man page :)

I can only thank you for what you are doing here.

Adam

**Comment by masmu** [comment]
You are welcome!

Currently working on it... Due to the lack of a working VPN I cannot test this myself.
Would you test this for me tomorrow?

**Comment by AdamNo** [comment]
Sure, i would like to contribute.

**Comment by masmu** [comment]
So, I found an interesting bug when coding that feature... a bug I was on the hunt a long time for :smile: 

Please try out that [branch](https://github.com/masmu/pulseaudio-dlna/tree/feature/ip-based-host-address), but you will need a new dependency: `python-netaddr`

**Comment by AdamNo** [comment]
Nice that you could find in addition an old bug :)

I just installed branch "pulseaudio-dlna-feature-ip-based-host-address".

It's working out of the Box having VPN enabled!

But there is a minor flaw displaying the IP.
"pulseaudio_dlna.application                    INFO     Using localhost: :8080"
In both cases. With and without VPN enabled.

The complete log:
http://pastebin.com/zsxSztvg

**Comment by masmu** [comment]
Great! So, expect this in the next release. I'll merge a few things right away into master.

The display thing is intended. I am not binding sockets to a specific host address anymore. So, the void before `:8080` means all interfaces ... :grin:
If you use the `--host` option the whole address is being displayed.

Normally this is not a problem, since most device are hidden behind routers firewalls anyway.
For your setup you should consider if you use the `--host` option and bind it to your internal network address. 
If your VPN provider allows incoming connections **and** a guy would know that `/dWRuPSJ1dWlkOkJPNUVCTzVFLUYwMEQtRjAwRC1GRUVELTY4QzkwQkI4NjEwMCIsdHlwZT0iYnJpZGdlIg%3D%3D/stream.mp3` connection url, he could listen to your music too. :musical_note:

**Comment by masmu** [comment]
Nevermind, I now realized what you meant with minor flaw. Fixing it...

**Comment by AdamNo** [comment]
What about writing "0.0.0.0:8080" or "*:8080".
Something from my limited Network knowledge i could understand :)

I thought indeed you missed "something" because its void. But it was indented. I learned something :)
I am listening to GOA Psy-Trance. The most futuristic music possible. At least in my mind.
I guess most people would tune off … immediately ;)

But i'll set --host. 

Adam

**Comment by masmu** [comment]
The asterisk it should be :smiley:
