### ISSUE TITLE
Error in WAV file. No 'data' chunk marker.

### ISSUE THREAD

**Issue by joerg-krause** [masmu/pulseaudio-dlna#222]
I am using a self-build MPD and upmpdcli for rendering the audio stream coming from pulseaudio-dlna. All encoders work fine except wav. This is the error I get from the MPD log:

```
sndfile: sf_open_virtual() failed: Error in WAV file. No 'data' chunk marker.
```

So MPD uses libsndfile as backend for WAV files.

pulseaudio prints the following encoder information:

```
Starting processes "parec --format=s16le -d hbm109510_dlna.monitor | sox -t raw -b 16 -e signed -c 2 -r 44100 - -t wav -b 16 -e signed -c 2 -r 44100 -L -"
```

**Comment by masmu** [comment]
I have no idea what you are doing. Could you please provide a little bit more info about your setup?

**Comment by joerg-krause** [comment]
Sorry for late reply.

I build MPD and upmpdcli from sources (so, no distro packages). MPD uses libsndfile for rendering wav files. Upmpdcli is used as a UPnP media renderer on top of MPD.

**Comment by masmu** [comment]
Sorry for my late reply too :smile:.

Well, as far as I understood you are basically running a _mpd_ server which is acting as a _UPNP media render_ through _upmpdcli_. I guess your speakers are not attached to the host computer _mpd_ runs on and therefore you want _pulseaudio-dlna_ to forward that stream to a _UPNP device_ or a _Chromecast_.

If I am right, you can leave out _upmpdcli_ from the setup description ... because it is just about controlling the _mpd_ server. _mpd_ is reading the audio files and playing them through _pulseaudio_. _pulseaudio-dlna_ should read the raw audio stream from it, encode it to _wav_ and serve the stream via HTTP. Correct?
