### ISSUE TITLE
Need some Help -- Pa-DLNA not discoverable on network

### ISSUE THREAD

**Issue by ustreedee** [masmu/pulseaudio-dlna#230]
Hi:

I have some audio coming in on the LINE-IN audio input on my Raspberry Pi, and I would like to use DLNA Server to stream it to a DLNA player.

I setup your PulseAudio-DLNA app on my Raspberry Pi and it seems to be installed and running.  I have Pulse-Audio also setup.  And also paprefs, and selected it to be discoverable on the network.  However, when I use my Playstation3 (PS3) to find a mediaplayer, it does not show up.  I have other DLNA media players which show up on the PS3, but the PA-DLNA is not showing up.

I'm not sure what I might be doing wrong here.

**Comment by prahal** [comment]
Mind I am a user.

To me paprefs "make local sound devices discoverable as DLNA UPnP Media server " pulseaudio-dlna are not related. 
To me pa dlna manages the stream (wraps both provider and controller) and the player grabs from pa dlna.  On the contrary, paprefs only make the sound stream available as a provider.

Here pa dlna was telling playing , the DLNA player was telling it  was playing the computer stream .... but no sound (turned out I had to let the player retrieves the data from pulseaudio-dlna ... that is open port 8080 on the computer firewall ).

UPnP  device discovery is about port 1900 udp ,  239.255.255.250 . It boils down to SSDP protocol.
Those keywords should help further close the issue.

NB: I did not manage to make use of pulseaudio paprefs built-in DLNA Media server option as of now.
Though this is unrelated and out of topic.


PS: So: pa-dlna is a controller that bind the provider (the sound stream from pulseaudio)  to a renderer (the DLNA player, here RuneAudio). 
While paprefs option let another controller bind the "sound device"  (mutated as a DLNA provider) to a renderer (the DLNA player).

**Comment by masmu** [comment]
> To me paprefs "make local sound devices discoverable as DLNA UPnP Media server " pulseaudio-dlna are not related. 

Correct.

@ustreedee You are using it the wrong way. _pulseaudio-dlna_ is not a complete DLNA-Server.
It finds DLNA clients which can be instructed to play streams. So e.g. your PS3 must have a player which allows remote control. _pulseaudio-dlna_ finds devices on your network which do so and instruct them to play a stream.
