### ISSUE TITLE
Create a service to autostart pulseaudio-dlna with user session

### ISSUE THREAD

**Issue by mhalano** [masmu/pulseaudio-dlna#233]
Could be a good idea create a .desktop file or integrate with PulseAudio so the command pulseaudio-dlna executes with user session. Maybe an option '--start-with-user-session' which creates a file under ~/.config/autostart to start automatically.

**Comment by masmu** [comment]
Perhaps I am wrong in this regard, but since there are several service systems such as _system v_, _system d_ I think this is a problem every distribution has to solve for them self. And therefore it is the job of package maintainers.

I always wanted to include a service file for my own packages, but if do in the next release it would cause a lot of trouble for people after upgrading to those packages. Thats the main reason for me to leave out a service file in my own packages.

**Comment by raphaelh** [comment]
Here is **pulseaudio-dlna.desktop** from Gentoo package : https://gitweb.gentoo.org/repo/gentoo.git/tree/net-misc/pulseaudio-dlna

```
[Desktop Entry]
Name=Pulseaudio DLNA
Type=Application
Comment=A lightweight streaming server which brings DLNA / UPNP and Chromecast support to PulseAudio and Linux
Exec=sh -c "pkill pulseaudio-dlna; pulseaudio-dlna --request-timeout=30"
Terminal=false
Categories=
NoDisplay=true
StartupNotify=false
```
Installed in **/usr/share/applications/pulseaudio-dlna.desktop**

**Comment by xmbwd** [comment]
In Ubuntu 16.04 (and similar distros), Startup Applications works for me.  Just create a new startup and put this in: pulseaudio-dlna --codec mp3 --encoder-backend=ffmpeg (or whatever works for you).

**Comment by mhalano** [comment]
@masmu
I have the ultimate solution for this, please consider with love. Systemd has user services. Acts like a regular service but is managed by users. It's perfect for daemons which need to be executed by a regular user instead the root. An application with this feature is called Syncthing. Basically the .service file is put on /lib/systemd/user. More informations can be found on https://wiki.archlinux.org/index.php/Systemd/User

**Comment by victornoel** [comment]
@masmu it would make sense to distribute some startup script that is well configured, for example for systemd since it is kind of one of the most used, and then let package maintainer do something with it (or not).
As @mhalano suggest, a user script would make sense, but I don't think that it is much different than a non-user script... not sure :)

**Comment by masmu** [comment]
@mhalano, @victornoel : Yeah, thanks for the tip, I guess I will do it like that. I just have to insert some code to prevent multiple startups, since a lot of users will already have working startup solutions.

**Comment by victornoel** [comment]
@masmu I don't think you should even worry about that. Just provide a working systemd service file and let packagers worry about the rest, no?

**Comment by masmu** [comment]
@victornoel If I don't update the code to handle multiple startups (perhaps with a nice explanation) I know exactly where people start to complain :wink: ...

**Comment by masmu** [comment]
The check for multiple startups is now in current master and will be in the next release. So expect a service file...

**Comment by vKnmnn** [comment]
Hi, i just wanted to check in on that service. any news?
