### ISSUE TITLE
noise

### ISSUE THREAD

**Issue by mc007** [masmu/pulseaudio-dlna#24]
Hi,
currently its playing music with quite a quality loss, there is an incredible noise when playing over dlna. I am on Ubuntu-14 and I stream to Marantz-5007, over net cable. 

Any suggestions? I see there are some python files with encoding settings. Do you know where are they located after the ppa installation? I guess I can find them with lsof.

thank you,
guenter

**Comment by masmu** [comment]
Do you use a special encoder or the default one (_lame_)?

I suggest you try to play with different encoders. (```--encoder``` flag)

If that does not help, change some encoder settings as suggested by yourself.
You can find the encoder settings at
```/usr/lib/python2.7/dist-packages/pulseaudio_dlna/upnp/server.py``` line 147 - 160.

**Comment by mc007** [comment]
thanks, removing -b 320 in the defaults for lame did work. flac and the others didn't work on marantz.

**Comment by mc007** [comment]
ah, sorry, i made some further tests and there is still a slight over amplification compared when playing the same track through iphone to Marantz. I tried all encoders and various settings but I don't get it really as on the iphone. Is it possible that Python could interfear with that stream ? I don't wanna bother you, its just I'd love to get max. quality out of this. Its a very contribution btw. I was looking very long for this here :-)

**Comment by masmu** [comment]
I am actually not sure.

What i am basically doing is that i record all sound via _parec_ and pipe it to an encoder such as _lame_. So at this point there should not be any quality loss, besides the one which is a result of encoding. Then i am sending the encoded bytes through HTTP to the DLNA device. At this point there should be any no quality loss, since TCP does not loose packets or stuff.

When i am googling for _Marantz-5007_, i get different search results. There are some which say, this device can only handle mp3 streaming. Others like the manufacturers [homepage](http://www.marantz.de/de/products/pages/productdetails.aspx?catid=airplayproducts&subcatid=avreceiver&productid=sr5007) proclaim, that it can also play 
```Network Audio: MP3 / WAV / AAC / FLAC / WMA```.
So, since i am not owning that device, i cannot find out which is acutally true. Perhaps this is a firmware thing, so that later firmwares can play more codecs.
If it can play _FLAC_ i would go with this, since with the right settings it is a lossless codec.
_WAV_ is always lossless, but it is also a bit antiquated. But i got feedback, that some people got the best results with that.
If not, try to tweak your _LAME_ settings. I don't know what you mean with _slight over amplification_, but i think that you can figure out which settings are best.

The last thing i can think of is, that perhaps some volume settings in your OS is causing the trouble. You know there is a _main volume mixer_, and there are _volume mixers_ for every application which is actually playing sound. Install ```pavucontrol``` and try to lower the _main volume mixer_ and increase the _application volume mixer_ for the application which is acually playing.

I am currently doing a complete rewrite of the streaming server of _pulseaudio-dlna_. But i don't expect better quality, but less latency and less CPU usage on your computer.

**Comment by masmu** [comment]
@mc007 bump

**Comment by mc007** [comment]
wow, thanks for the detailed help! actually only lame came through. the mixer was my first guess too, so i tried quite some stuff but no. the marantz and also my speakers are actually top quality, iphone play proved it...ok then, i will dig deeper then. 

good to hear about latency problem. I got also some ideas to integrate this library in my IDE for home-automation/theater (https://github.com/mc007/xbox-app/blob/master/misc/screenshots/SCREENSHOTS.md); 

thank you again, will let you about some outcome :+1:

**Comment by masmu** [comment]
@mc007 

No deceitful hopes. There will always be a latency, cause its a result of the network buffer such devices are using. But perhaps i can decrease it a bit.

I never doubt that your device and your speakers are not top quality. When i see the price, i was kind of expecting that :smile: 
But you cannot compare the Airplay stuff with the DLNA one. Those 2 protocols are managed differently by the firmware of your device. So, its always also up to the quality of the manufacturers implementation of these. The devices which i am using have a very good implementation of both. There is not any difference. That does not mean the DLNA software implementation of your device is a bad one. I would not give up hope. Especially with lame, you can do hundrets of combinations.
Do a ```man lame``` to see yourself.
If lame really cannot bringt the desired results, you can try another mp3 encoder. Try [ffmpeg](https://www.ffmpeg.org/) for example. You just have to figure out the right command.
I find it hard to believe that you cannot bring a device of that price to play maximum quality with DLNA. So, just don't give up ...

I am curious to see what you are planning with your home-automation/theater, so keep me posted!

Did you check about the firmware version?
