### ISSUE TITLE
pulseaudio-dlna Open/LibreElec Add-On

### ISSUE THREAD

**Issue by guitarhead** [masmu/pulseaudio-dlna#244]
Is there any chance to get this working in Open/LibreElec to pipe all audio to an dlna device?

Like to get Google Play Audio Add-On working with dlna.

**Comment by masmu** [comment]
Well, I actually did not try this myself but I give it a good chance. You have to install `pip` first, then install all the dependencies and after this it should run.

Since there is no package manager in _LibreElec_ you have to [bootstrap `pip`](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py).
The real problem is how to install the encoders (_sox_, _lame_, ...) in _LibreElec_. I guess the easiest way is to install some static arm binarys if you find those precompiled for your Pi.
