### ISSUE TITLE
Is there a way to echo song playing on player

### ISSUE THREAD

**Issue by alrayyes** [masmu/pulseaudio-dlna#259]
Hi,

I use pulseaudio-dlna with cmus to stream to my reciever. Is there a way to echo currently playing data on the receiver?

**Comment by masmu** [comment]
Hi,

Do you mean echoed on your computer? If yes, I am pretty sure this is possible via _pulseaudio_ commandline fu. But it would be not in sync with stream send to the device.

**Comment by alrayyes** [comment]
No I mean on the device. Lisa there any way I can tell pulseauduio_dlna "now push this string to the device"? Then it would be possible to push now playing id3 tag info, which would look neater than application name.

**Comment by masmu** [comment]
Ah okay. It is not possible with DLNA devices. The specification does not allow you to set the currents song meta information. You can just set it once when you registering the stream. If you registering the stream again (with different meta data) after a song on your computer finished the current stream collapses and a new one is being established, resulting in a break while listening.

It is possible with Chromecast in general. But you would need to write an own _Chromecast MediaPlayer application_, since the default one also lacks the ability to set the meta information.

**Comment by alrayyes** [comment]
That's a shame, would have been nice.

**Comment by masmu** [comment]
True. Tried it a year ago to exactly implement the feature you are asking for. I also implemented the Icy-meta data for testing, but it showed that there are not many devices supporting that.
So this would always be a feature which is not working for most devices (and might create some compatibility problems) and since I really like consistent feature sets over both plugins (DLNA & Chromecast) I discarded that idea.

**Comment by alrayyes** [comment]
Well in theory it would be doable if the mp3 player directly implemented pulseaudio-dlna and created a new stream for every mp3 without transcoding. That's the only way I can think of the log being bearable.

It's a shame the dlna people can't get with the times. Airplay has been capable of this for years.

**Comment by masmu** [comment]
> Well in theory it would be doable if the mp3 player directly implemented pulseaudio-dlna and created a new stream for every mp3 without transcoding. That's the only way I can think of the log being bearable.

Yeah, but it would be another project. That project aims to create virtual sound cards for streaming devices in your network. For that reason it may not understand what is being played right now. It just streams everything which is played on the soundcard. Regardless if it is a song or just a system notification sound. Everything is being streamed.
You are right, you could actually create a mp3 player with a lot of the existing code exactly doing what you want. But you would have the buffering between each song all over again.

> It's a shame the dlna people can't get with the times. Airplay has been capable of this for years.

Well, it is as it is. I highly doubt there would be a large variety of devices implementing that new standard. And to be fair, it is pretty exotic what we are doing here.
