### ISSUE TITLE
Playback over network very choppy

### ISSUE THREAD

**Issue by BaReinhard** [masmu/pulseaudio-dlna#279]
So, this may just be an issue of how I have things setup and not necessarily due to the repo itself.

That being said, I just want to make sure that is the case.

I am essentially trying to create a multi-room audio setup in which I have multiple Raspberry Pi's setup throughout the house and have one main RPI running Ubuntu Mate that handles the bluetooth/airplay connections then uses pulseaudio to stream the playback over the sinks that DLNA creates from UPnP Renderers that are created by`gmediarender-resurrect` running on a Raspbian Jessie Lite Distro.

I was testing today with the main Pi with Ubuntu Mate just streaming audio from youtube to a remote pi running Raspbian Jessie Lite over WiFi. I initially tested it when the remote Pi was connected to the router via ethernet (everything sounded great), then I tested the remote Pi when it was only connected via WiFi and only 15ft away.(It was very choppy, cutting in and out).

Due to the choppy playback when on WiFi, I assume that this is network related, although I could be wrong.

Is this a known issue with the Raspberry Pi's, or should this issue be raised on `gmediarender-resurrect`? Is there any way to optimize `pulseaudio-dlna` to allow for this type of setup, or am I better off using some other configuration?

Aside from the choppy playback, this idea would have worked very well, allowing for a python GUI to control which sinks to combine and move the input to the proper sink.

**Comment by masmu** [comment]
I am using 2 wifi DLNA devices (D-Link DCH-M225/E) one of them running behind a wifi extender and I am not experiencing any choppy playback at all. But from time to time there are people reporting the same as you do. It is hard to tell what actually causes the problem and it needs further investigation from people having access to those network setups.

So, I added a new CLI option `--chunk-size` in a [branch](https://github.com/masmu/pulseaudio-dlna/tree/feature/chunk-size) which determines how many bytes are being sent in one bunch. I would recommend you to test some real low values like 128 and 512 and some higher ones as 8192, 16384 and 32768.
Furthermore you can play around with the `--codec` and `--bit-rate` option which both have a large influence on how much data needs to be transported overall. E.g. the wav codec needs a lot of data, mp3 does not.

Regarding your multi-room setup: Device groups are not supported for DLNA devices and probably never will be. The DLNA specification simply does not support that. There are some manufacturers such as _Raumfeld_ and _Sonos_ which did implement that feature on their own... But this is only compatible to their own devices.

If you want painless syncronized multi-room streaming, consider Chromecasts which are also supported by _pulseaudio-dlna_.

**Comment by BaReinhard** [comment]
Forgive my ignorance but what do you mean when you say device groups? I'm assuming that you may be talking about when you combine sinks into a single sink? Is this correct?

I'll play around the with CLI option and change the rates to see if that fixes things.

**Comment by masmu** [comment]
Yeah, exactly. The feature is called device grouping for Chromecasts. You can create a device group by using the Android application which creates a new virtual device representing all the other devices in that group. If you send a stream to that new virtual device all the devices starts to play.

**Comment by BaReinhard** [comment]
Thank you! This is exactly what I needed, and looking at the pricing and functionality, much easier to setup. Now the only issue I will have is outputting shairport-sync to pulseaudio.

**Comment by masmu** [comment]
shairport-sync is basically a receiver for iTunes streams right? If that is the case it will output on pulseaudio by default. Take a RPi, install shairport-sync and pulseaudio-dlna on it. Switch the audio stream shairport-sync generates to the Chromecast device group. Everytime the RPi recieves an iTunes stream it will pass that to pulseaudio-dlna which will stream it to all other Chromecasts.

**Comment by BaReinhard** [comment]
Earlier you mentioned that device groups are not supported, but it seems to me that you're saying that Chromecast device groups created by Google Home are supported?

**Comment by BaReinhard** [comment]
I actually went and bought two chrome cast audios (thanks to a Best Buy gift card) and tested with a group made with `Google Home` app. The playback worked flawlessly with shairport since run via `shairport-sync -o alsa -c pulse`. thanks for the awesome repo, this made multi room audio far cheaper and easier to setup. I plan to run a similar setup in a local gym setup (given I can make this work consistently) .

The basic setup was a single pi running Ubuntu MATE, which allows for shairport-sync to run and output to pulseaudio then move the sink to the Google home group. Depending how many groups you setup you can output to whatever multi room setup you want, the latency wasn't that bad with shairport but the latency with a2dp needs some finessing.

**Comment by masmu** [comment]
Thanks for the feedback! Glad that it works so well for you. But the credits for the multi-room support goes to Google I guess :wink: 

Basically you created an adapter to stream from iTunes to Chromecasts with the help of a RPi. Just some final hints. In case the stream collapses... which might happen from time to time, because of the unreliability of wifi ... check out the `--auto-reconnect` flag.

If this isn't too much to ask for, could you please do the testings with the DLNA RPis and the `--chunk-size` option and keep me posted if this has an effect for you? I am kind of relying on those information because I cannot reproduce that problem myself.

**Comment by BaReinhard** [comment]
Yes, the multiroom credit could go to google as they made it so much easier, but pulseaudio also has builtin modules to combine sinks into one so I am sure there would be a work around even without google :smile: .

Unfortunately, I am no longer using the setup which caused the chopping. Instead of using another RPI with `gmediarender-resurrect` I just went with the chromecasts. I believe the issue could be any number of things, but it's likely due to too much being requested on the Pi and possibly a not a big enough power supply. If I do setup another Pi I will definitely try out the flags and options.

Is there a log setting in `pulseaudio-dlna` in which I can use when testing?

**Comment by masmu** [comment]
> but pulseaudio also has builtin modules to combine sinks into one so I am sure there would be a work around even without google.

Sadly it is not (it is but it is not synchronized). You can combine sinks, but each DLNA renderer starts to play on their own so that they are out of sync. And pulseaudio does not offer any options to control the delays... (This is a very popular question people asking me)

> Is there a log setting in pulseaudio-dlna in which I can use when testing?

What do you mean by log setting? Regarding the `--chunk-size` option you don't need to enable verbose logs (which could be done by `--debug`). This would be just a testing and reporting thing, like: Ok, `--chunk-size 512` does this ... `--chunk-size ...` has the effect that ...

**Comment by tristan-k** [comment]
I will have to dig out this issue because I'm having crazzy choppy sound with a ArchLinux system and the latest `gmrender-resurrect `and `pulseaudio-dlna`. I played around with the bitrate and codecs settings but the connection is still choppy. Where did the `--chunk-size` option go because the [branch](https://github.com/masmu/pulseaudio-dlna/tree/feature/chunk-size) isnt there anymore?
