### ISSUE TITLE
Chromecast Audio Receiver

### ISSUE THREAD

**Issue by mbt28** [masmu/pulseaudio-dlna#281]
Hello,

I would like to use my omega 2 wifi linux device as chromecast audio receiver. Is it possible to configure it with your application?

Thanks

**Comment by masmu** [comment]
This software streams to DLNA and Chromecasts. So if you are able to install some Chromecast firmware on that device, then the answer is yes.
But since the firmware for Chromecasts is closed source I highly doubt that.

If you don't rely on multi-room playback you can install a software DLNA renderer on your device, like [gmrender-resurrect](http://github.com/hzeller/gmrender-resurrect) or [cocy](https://github.com/mnlipp/CoCy).
