### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by kelunik** [masmu/pulseaudio-dlna#29]
When starting `pulseaudio-dlna`, I get the following error:
```
Traceback (most recent call last):
  File "bin/pulseaudio-dlna", line 9, in <module>
    load_entry_point('pulseaudio-dlna==0.3.4', 'console_scripts', 'pulseaudio-dlna')()
  File ".../masmu/pulseaudio-dlna/pulseaudio_dlna/__main__.py", line 160, in main
    pulseaudio_dlna.startup()
  File ".../masmu/pulseaudio-dlna/pulseaudio_dlna/__main__.py", line 121, in startup
    print(upnp_device)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 32: ordinal not in range(128)
```

**Comment by masmu** [comment]
Which distribution are you using? Ubuntu? Version?

Could you paste the output of every following command?
- ```locale```
- ```locale -a```
- ```python2 -c 'import sys; print(sys.stdin.encoding); print(sys.stdout.encoding)'```

**Comment by kelunik** [comment]
Yes, it's Ubuntu 14.10. You can find the commands output at http://paste.jesse-obrien.ca/1S2W.

**Comment by masmu** [comment]
Does your error still persist? I am asking because you made the pull request with the successfully tested _Raumfeld_ devices.

Your error normally just appears on terminals which encoding is set to _ascii_ or stuff like that.
Because of your error message i was convinced your terminals encoding is set to `ascii`.
But the output of `python2 -c 'import sys; print(sys.stdin.encoding); print(sys.stdout.encoding)'` states its set to `utf-8`.

The application tries to print the name of the device ... and there is the german letter `ü` included. Thats normally not a problem, because your terminal encoding is set to `utf-8`. There is a representation in utf-8 for `ü` and so it can be printed.
In `ascii` there is no `ü` and if your terminal is set to it, it failes doing that.

So, what confuses me... why the different encodings of the error message and the code snippet i gave you? Did you tried it on another computer?

**Comment by kelunik** [comment]
No, it's all on the same computer with same terminal settings. I added it as successful tested, because it worked. I just had to add a filter so that other device isn't scanned further and the error doesn't appear.

**Comment by masmu** [comment]
Thats wired. You are the first one with that problem.
I want dig into that deeper.
Can you paste a debug log in a file a paste it somewhere?
```pulseaudio-dlna --debug &> debug.log ```

Perhaps i can find something ...

**Comment by kelunik** [comment]
Unfortunately, this wasn't at my home, so we'll have to wait until mid of may until I can provide a debug log.

**Comment by masmu** [comment]
@kelunik 
Don't worry. Just provide it the next time you are there.

**Comment by masmu** [comment]
Closed due to inactivity

**Comment by kelunik** [comment]
I totally forgot about this, but I got a debug log last time: http://pastie.org/private/hzvoi8nunayjnizgui2tdq

**Comment by masmu** [comment]
Could you do another ```python2 -c 'import locale; print(locale.getpreferredencoding())'``` ?

I just release _0.4.0_. Could you test it with that new version again?

**Comment by kelunik** [comment]
```
python2 -c 'import locale; print(locale.getpreferredencoding())'
UTF-8
```
Unfortunately, I can't test until September, but I'll do it then.

**Comment by masmu** [comment]
Ok :smile: 

Please execute that command also on the machine which is failing.

**Comment by kelunik** [comment]
That's on my notebook, so it _is_ the machine which is failing. ;-)

**Comment by masmu** [comment]
So, i was suspecting that the issue occurs on a machine where you will have access again in September. Where is my mistake?

**Comment by kelunik** [comment]
The network with the media renderer is the one I won't have access to until September. And I can't run commands on that device.

**Comment by masmu** [comment]
Ok, the output of your notebook is fine. Lets see what the new version does ...

**Comment by masmu** [comment]
Closed due to inactivity.
