### ISSUE TITLE
pulseaudio_dlna.plugins.upnp.renderer: No valid XML returned

### ISSUE THREAD

**Issue by rohusan** [masmu/pulseaudio-dlna#318]
I try to control Yamaha Receiver RX-3900. Once I start pulseaudio-dlna this error shows up:

pulseaudio_dlna.plugins.upnp.renderer          ERROR    No valid XML returned from http://10.10.10.6/MediaRenderer/desc.xml.

This happens for package installed and git clone as well. Did try this [code](https://github.com/masmu/pulseaudio-dlna/issues/216#issuecomment-249179973) but didn't help.

[yamaha-rx-3900-desc.txt](https://github.com/masmu/pulseaudio-dlna/files/1131436/yamaha-rx-3900-desc.txt)

**Comment by masmu** [comment]
Your device does not implement the service `urn:schemas-upnp-org:service:AVTransport` and is therefore not remote controllable. I guess you can actually access other DLNA devices from it, but since it is missing that service I doubt that other devices can control it.
It implements `urn:yamaha-com:service:YamahaRemoteControl:2` which is something proprietary of Yamaha and you might make it run if you invest some time and analyze their protocol.

I am sorry.

**Comment by rohusan** [comment]
Thanks, that makes sense. I might buy a newer av receiver then.
