### ISSUE TITLE
Rasberry Pi support

### ISSUE THREAD

**Issue by roizcorp** [masmu/pulseaudio-dlna#34]
Hi,

I have a use case in which I would like to watch a movie in the Kodi (on Raspberry pi, running Archlinux Arm) and wish to stream the sound into my phone, so potentially I will hook headphones into the phone and will be able to listen to the movie without interupting anyone else

So far I think we are lacking dependencies, can you make sense for me if your project could do such a thing? and whether you will be able to help me getting my use case working?

**Comment by masmu** [comment]
You can, but your sound will be delayed. You will have to turn your phone into a DLNA renderer. For Android there is e.g. BubbleUPnP which can do that. It will act as a reciever for pulseaudio-dlna.
But as i said, your sound will get streamed and since that it will have a delay. Depending on the choosen encoder, the bitrate and your wifi this delay will be between 2 and 10 seconds.

**Comment by roizcorp** [comment]
Luckly I have BubbleUPnP already :-), However you ask for some python packages that are not available in Archlinux Arm such as python-setproctitle
As for the delay, Kodi has a feature that help you to collaborate the sync between video and audio

**Comment by masmu** [comment]
I ask for some python packages which are not available in archlinux? Sorry, i do not understand ;)

**Comment by roizcorp** [comment]
the dependcies python packages list...never mind....I will take it from here

Thanks though
