### ISSUE TITLE
Add link to Archlinux AUR

### ISSUE THREAD

**Issue by yegorius** [masmu/pulseaudio-dlna#38]
Hello,
I prepared PKGBUILD for Archlinux, it can be found here https://aur.archlinux.org/packages/pulseaudio-dlna/
It would be convenient if README includes this link for Archlinux users.

**Comment by masmu** [comment]
Thanks for your package.
I hope that you are okay with sending complains about the package right back to you :smile: 

By the way... I think you forget _sox_ as a dependency, right?

**Comment by yegorius** [comment]
Sure, I will maintain the package in the near future.
Yes, I forgot about sox, but is this an optional or required dependency?

**Comment by masmu** [comment]
In the moment _sox_ is a must have dependency. It is used for _wav_ encoding. If you don't install it but use the _wav_ encoder, the application will crash.

But i am planning to make all encoders optional. So, if you don't install _lame_ you won't be able to stream _mp3_ files. If you don't install _sox_ you won't be able to stream _wav_. And so on ...

But i recommend to not make those _optional_. If you don't install any of these the application will be useless, because its not able to encode any data.
Devices support different codecs. So, you should provide as many as you can, to increase the chance that there is one encoder which can be handled by the device.
