### ISSUE TITLE
when it is available for ubuntu 20.04 ?

### ISSUE THREAD

**Issue by JohanvdS** [masmu/pulseaudio-dlna#401]
I use this tool for many years now and i love it, but since i installed a new fresh ubuntu. I cannot acces this. comes this tool back ? or in the repositories?

Yours

Johan

**Comment by Faberix** [comment]
It is probably not available for Ubuntu 20.04 because it is written in Python 2, which is end-of-life. 
I have also used pulseaudio-dlna for some time now and would like it being available for 20.04. However, I doubt it will be available soon as making it available on 20.04 would require porting it to Python 3 and that all dependencies have Python 3 versions. Although there are automated conversion tools available, it will probably take some time until it is ported (assuming the developer is still maintaining this repository). If you (or anyone else) have enough spare time (which I don't) and know Python, you could port it yourself...

**Comment by polyzen** [comment]
Referencing #262

**Comment by emembrives** [comment]
I ported the project to python3.8 and tested with Chromecast. See this pull request https://github.com/masmu/pulseaudio-dlna/pull/404.

I see there is at least another pull requests about porting to python3, but disabling Chromecast. Depending on what you need, you may be able to use one or the other.

**Comment by avodonosov** [comment]
Based on the instructions from readme, I've installed it from git on Ubuntu 20.04 with the following commands:

```
sudo apt-get install python2.7 python-setuptools python-dbus python-docopt python-setproctitle python-gi python-protobuf python-psutil python-concurrent.futures python-chardet python-netifaces python-netaddr python-lxml vorbis-tools sox lame flac faac opus-tools

sudo apt-get install python2-dev
sudo apt-get install virtualenv
git clone https://github.com/masmu/pulseaudio-dlna.git
cd pulseaudio-dlna/
Edit setup.py and replace zeroconf to zeroconf-py2compat:
        #"zeroconf >= 0.17.4",
        "zeroconf-py2compat >= 0.19.6",
make
./bin/pulseaudio-dlna
```

**Comment by cperreault** [comment]
Hello, I tried to run a version built locally (`bin/pulseaudio-dlna`), either from this repository with the previous modification indicated in the previous comment by @avodonosov, and from @emembrives's `2to3` branch. In both cases, I see only messages in the terminal and no window is created/displayed. Running with `--debug`, I can see it searching for devices, such as detecting my Samsung TV, but it stops at:
`pulseaudio_dlna.discover    INFO    SSDPDiscover.search()`

I am new to this project. I try it as an alternative to mkchromecast, which streams the whole system audio, but suffers currently from a 20 seconds lag, so I can select a specific application to stream to a Chromecast audio. I am using Ubuntu 20.04. Thanks in advance for any help!

**Comment by avodonosov** [comment]
@cperreault 
>  I see only messages in the terminal and no window is created/displayed

What window do you expect to be created?

BTW, about lag - I am using pulseaudio-dlna to stream music a Volumio running on a single board computer (rock64) connected to an amplifier. And I have several seconds lag too. Don't know if the lag is caused by Volumio or by pulseaudio_dlna, or both...  I wish I could fix it.

So, from this experience, there is no guarantee you won't have lag with pulseaudio_dlna

**Comment by mrshll** [comment]
@cperreault for a bit more info: no window will be created, but you'll find it in your list of output devices in your sound settings (might differ depending on your setup)
![image](https://user-images.githubusercontent.com/339996/85129186-aec34b80-b200-11ea-86a6-e60396634b1a.png)

**Comment by cperreault** [comment]
Thanks @avodonosov and @mmoutenot! The image at the main page of the project just instinctively made me think that it had a GUI, but now I realize that it is `pavucontrol`, executed independently.
Thanks for your help, I can now stream to my Chromecast Audio! 

I experience the same ~20 seconds lag now with `pulseaudio-dlna` than with `mkchromecast`. A recent hacky change in `mkchromecast` is supposed to cut that in half. I retried it but I realized that I did not tried `mkchromecast` since my Ubuntu 20.04 upgrade, and that, in fact, there is now an error connecting to my Chromecast Audio device (it detects it, but cannot connect).

So for now I am happy with `pulseaudio-dlna`, just realizing that I can broadcast a specific app and not the whole system. I will dig more into it. At least I can now use my Chromecast Audio for my outdoor music instead of my old flaky USB FM emitter. The thing I like though about my FM emitter is that I can play the same music outside and inside. I will be looking into solutions to group 2 Chromecast Audio. `mkchromecast` is supposed to support multi-room group playback and I am not sure `pulseaudio-dlna` does it.

Anyway, thanks again for your help. The main subject here is compatibility with Ubuntu 20.04. I guess migrating to Python 3 is a no brainer.

**Comment by polyzen** [comment]
> So for now I am happy with `pulseaudio-dlna`, just realizing that I can broadcast a specific app and not the whole system.

You get that same functionality with using `mkchromecast`'s `parec` backend.

>  I will be looking into solutions to group 2 Chromecast Audio. `mkchromecast` is supposed to support multi-room group playback and I am not sure `pulseaudio-dlna` does it.

Apparently there should be group support:
https://github.com/masmu/pulseaudio-dlna/issues/152

Perhaps search for issues relating to "group". If you're using a Python 3 build, perhaps check the pychromecast repo for how/if groups work. I cast to Sonos devices which implement grouping on their end.

**Comment by avodonosov** [comment]
@cperreault, some info about the playback lag: I'm streaming to my Volumeo DLNA from a mobile phone (using BubbleUPnP), and there is no delay, the playback / pause are instant. So I conclude the delay I have with pulseaudio_dlna comes from pulseaudio_dlna, not from Volumeo.

**Comment by nsk7even** [comment]
I used the `python3` branch on my ubuntu 20.04 system and it works.
Just be sure to clone a fresh repo, if you made any attempts using python2 prior!

**Comment by apmic** [comment]
@nsk7even
> I used the `python3` branch on my ubuntu 20.04 system and it works.
> Just be sure to clone a fresh repo, if you made any attempts using python2 prior!

Can you please provide a guide how to do this?

**Comment by nsk7even** [comment]
> @nsk7even
> 
> > I used the `python3` branch on my ubuntu 20.04 system and it works.
> > Just be sure to clone a fresh repo, if you made any attempts using python2 prior!
> 
> Can you please provide a guide how to do this?

Just from my mind:

1. git clone https://github.com/masmu/pulseaudio-dlna.git
2. git checkout python3
3. make

refer to the README for more information

**Comment by Lumipyry** [comment]
Just today installed from Debian packages [https://packages.debian.org/sid/all/pulseaudio-dlna/download](https://packages.debian.org/sid/all/pulseaudio-dlna/download) with Gdebi and works fine in Kubuntu 20.10.!!!

Previously when I installed the same package without Gdebi it did not work (Gdebi finds and installs all the dependencies as well).

Gdebi seems to have found all the necessary dependencies or someone has added them to Debian package.

Before that, I used @avodonosov's instructions and that worked as well (thanks Anton) (It was Kubuntu 20.04, I don't remember if I tryed it in Kubuntu 20.10), but installing with Gdebi is faster and easyer.

**Comment by oldfryeguy** [comment]
I was able to get pulseaudio-dlna installed on Kubuntu 20.04 using avodonosov's instructions and it tells me it is running. Unfortunately I do not have any additional devices available in pulse audio settings.
Any suggestions?

**Comment by Lumipyry** [comment]
@oldfryeguy You can try my solution: Install Gdebi (good about Gdebi: It finds and installs all the dependencies as well) and then download the Debian-package from [ https://packages.debian.org/sid/all/pulseaudio-dlna/download]( https://packages.debian.org/sid/all/pulseaudio-dlna/download)  with Gdebi. Should work.

**I just read today, that Pulseaudio-dlna works again installed with Discover or with `sudo apt install pulseaudio-dlna`** (or Muon Package Manager, or maybe the person who said this installed it with Synaptic) (in Kubuntu 20.10). This is the easiest way of course, if it works. (Previously did not work in Kubuntu 20.10).

Because Synaptic is Debian package manager, it may install the same package as I downloaded from the Debian web-page, but I'm not sure. Discover and Muon use Ubuntu repositories and therefore different packages and that may be the reason why Discover and Muon pulseaudio-dlna packages don't/didn't work (the primary problem was, that the packages didn't have the needed python3 dependencies, and the Debian package probably had been updated earlier).

You do know, that you have to type command `pulseaudio-dlna` in terminal (Konsole) to execute pulseaudio-dlna?
And it has to be done every time you turn on your computer.
From your text "it tells me it is running" you have done this already; This may help some other users, because sometimes one forgets to do the obvious.

Next, check if the Google Chomecast device shows in your mobile phone's Google Home-app? If not, boot the Chromecast device.

Oh hey: Pavucontrol needs to be installed as well. I don't remember if it comes automatically in Kubuntu basic install.
If you downloaded all the dependencies, you should of course have it already.
 
When pulseaudio-dlna works correctly, you don't have to open pulseaudio settings. The Chromecast device(s) is (are) shown in Volume-menu in menubar.

Here's a good hint for everyone: Put pulseaudio-dlna to autostart list in System Setting in Kubuntu (from Start and Stop - Menu, Autostart submenu) so it starts automatically when computer in turned on. I also have Yakuake-terminal on the same list.

**Comment by Lumipyry** [comment]
.................................................................................................................................................................................................

This is a good opportunity for me to thank You, Massimo Mund (with user name masmu), who programmed this all and made it possible for us others to use this program to get sound and video casted over WiFi network to dlna receivers!!!!!!!!!!

If You ever read this, Massimo,
Se leggi mai questo, Massimo,
Tuhannesti kiitoksia (en la lingua finlandese, in finnish language) = Mille Grazie = Thousands of Thanks

Io voglio, que tu a una molto magnifico vita!

P.S. I'm not sure whether your native language is (german) deutch or (italian) italiana, so:

Wenn Sie das jemals liest, Massimo,
Tausenden Danken für dich, Massimo

Ich möchte, daß Sie ein sehr großartiges Leben hast!

Minä toivon, että Sinulle yksi hyvin upea elämä tulee!
(The text above is  a direct translation, not proper Suomi-language; the correct way to say the same thing is:

 Minä toivon, että Sinun elämästäsi tulee upeaa!

I just wrote the two different sentences to show, how Suomi language is written and spoken, if anyone is interested in (Suomi) Finnish language.
 
Mr. Sami Saarinen,
M.Sc. in Materials Science in Technology
Suomi, known as (Finlandia, Finnland, Finland, Finlande) abroad


.................................................................................................................................................................................................
