### ISSUE TITLE
Create DLNA/UPNP Group

### ISSUE THREAD

**Issue by ryanroth** [masmu/pulseaudio-dlna#42]
It would be helpful if there was the ability to create a group of speakers that appeared as one device rather than each target having to be a separate device. It would also be cool if you could assign the to channels ie; LF, RF, RR, LR, Center.

I was able to do this manually by joining sinks and assigning channels to each through pulse audio but it was difficult to do.

**Comment by masmu** [comment]
Can you describe the process of doing this with pulseaudio?

**Comment by ryanroth** [comment]
pacmd load-module module-combine-sink sink_name=combine sink_properties=device.description=myCombine slaves=remap50,remapLFE channel_map=front-left,center,front-right,rear-left,rear-right,lfe channels=6

**Comment by ryanroth** [comment]
That will create a new device called myCombine from the slaves

**Comment by masmu** [comment]
This is very cool.

Is your sound is sync? Because i guess every device recieves its own stream and therefore there its highly possible that they are not synchronous.

**Comment by ryanroth** [comment]
Mine were all in sync. My TV had the option to adjust the delay on it in pacontrol. It would be cool if you could work in audio delay/offset in the devices that are created my pulseaudio-dnla.

**Comment by masmu** [comment]
Which TV do you have and where is that option in pacontrol exactly?

What do you mean with your last sentence? :smiley:

**Comment by ryanroth** [comment]
A Sharp lcd running off hdmi. Expand advance under the volume slider. 

Ryan Roth

**Comment by masmu** [comment]
Okay, mine are not in sync. So that yours are in sync is by coincidence i guess. Or the sonos devices have some special feature which does that.

There is a major problem with that feature. As soon as you add the combine-sink pulseaudio constantly adds virtual streams for all the specified sinks.
Since pulseaudio-dlna reacts to those changes your devices will always play. There is no method in shutting them down as long as the combine-sink exists.
If you switch to another sink (e.g. to your HDMI monitor sink) the devices won't playback any sound anymore, because pulseaudio does not transmit any data to those virtual streams. But since the virtual streams will persists pulseaudio-dlna will still stream zero-data to your devices. You just don't hear it.

combine-sinks currently break the whole architecture :smile: , but i will play with it a bit to see what can be done.

**Comment by ryanroth** [comment]
Awesome. Thanks.

**Comment by masmu** [comment]
2 of them are. One self build via software and a chromecast.

**Comment by masmu** [comment]
I quickly hacked the basics in.

There is quite some stuff necessary to cheat the pulseaudio mechanics. No zones, no channels yet, just a new sink which plays on all found devices.
This is just a proof of concept, don't expect too much. But in contrast to your solution, it will stop playing if you give the order.

You can checkout the result [here](https://github.com/masmu/pulseaudio-dlna/tree/feature/combined-sinks).

**Comment by masmu** [comment]
I have just seen your request for the the latency offset. As is seems thats not possible because of pulseaudio. See the post [here](http://lists.freedesktop.org/archives/pulseaudio-discuss/2013-November/019135.html). Summarized: Pulseaudio supports latency offset only for ALSA and bluetooth devices.

There is really nothing i can do about this, sorry.

**Comment by polyzen** [comment]
The branch for combined sinks still exists. I suppose it was never merged as it didn't get testing?

**Comment by polyzen** [comment]
Note: This is not needed (perhaps not even ideal?) if you want to use multiple Sonos speakers as one. You can use a Sonos client (eg. [socos](https://github.com/SoCo/socos)) to choose a room/speaker and group as you wish. Choose that room/speaker as your Pulse output.

**Comment by SpineEyE** [comment]
It would be great to have this feature even without latency settings!

The pacmd commands by ryanroth somehow don't work for me: I created a combined sink of my analog output and a dlna renderer in the same LAN. I can play music on both of them separately but when I select the combined sink as output, `pulseaudio-dlna` instructs the dlna device to stop playing. `pavucontrol` shows that there should be audio playing on both of them.

I tried to rebase the commit myself, but the code has changed so much that it's pretty hard without having worked on the project before. Do you think you have time to do this?

**Comment by rektide** [comment]
I wanted to run the following & get output on my chromecast & usb soundcard:

```
pacmd load-module module-combine-sink sink_name=output channels=2 adjust_time=1 slaves=my_chromecast,alsa_output.usb-Turtle_Beach_Blah_Blah.analog-stereo
```

The chromecast device does not output any audio though in this case. Even if it were out of sync, it would be very useful to have. Is there any way we can re-open this ticket, in some form?
