### ISSUE TITLE
HAME soundrouter discovery issue

### ISSUE THREAD

**Issue by billsbro** [masmu/pulseaudio-dlna#44]
I am using a Hame UPNP/DLNA soundrouter (http://hamedata.com/hamemusic/hamemusic-help.html) to stream sound over wifi to a regular stereo amp. The device works just fine with my droid smartphone and tablet, using the bubbleupnp app. To stream audio from my ubuntu 14.04 laptop your solution would be perfect. 

The discovery of the soundrouter works as long as I connect my laptop to the hame wifi network with its own IP range and SSID. This is different from the android devices that discover the soundrouter even if they are connected to the regular home wifi network.

**Comment by billsbro** [comment]
http://192.168.178.1 is the wifi modem
with WAN cable
dhcp server from http://192.168.178.10 on up

http://192.168.169.1/ is the soundrouter that has its own dhcp server, it is connected through wifi
(all you have to do, if I remember correctly, is connect to its splash page on that ip adress to set it up). It runs as a regular router to the internet as well but its less fast than the regular wifi modem, so I would prefer not to switch to it. 

System Info
Version    	v.20141204200204
WiFi SSID    	HameMusic_517a
Internet Configurations
WAN IP Address    	192.168.178.16	
Default Gateway    	192.168.178.1	
Primary Domain Server    	212.54.40.25	
Secondary Domain Server    	212.54.44.54	
Subnet Mask    	255.255.255.0

**Comment by masmu** [comment]
Well. I found finally some time to figure that out.

The device opens a second network (192.168.169.x) for its wifi devices. This is pretty unusual for that kind of devices. The solution is to set it to your current network (192.168.178.x)
But those kind of settings are not accessible via the normal web GUI.
But the device has a somehow hidden advanced configuration area. But due to their implementation is not possible to access this without some kind of hacks. This is clearly a bug in their firmware.

1) Open _Chrome_ and goto the _Settings_ Page.
![part1](https://cloud.githubusercontent.com/assets/7857307/8900188/b7053e02-343d-11e5-8b82-f37aa7e57fde.png)

2) Press F12 to open the Chrome developer extensions. Click on Console. Then add the following javascript in the console window and press ENTER.
```js
parent.HomeFrame.document.getElementById('advanced_settings').click()
```
![part2](https://cloud.githubusercontent.com/assets/7857307/8900189/b74f463c-343d-11e5-9aa7-277332b05473.png)

3) Press F12 to exit the Chrome developer extensions.
![part3](https://cloud.githubusercontent.com/assets/7857307/8900187/b704c22e-343d-11e5-8928-e406e0de1033.png)

In the advanced settings goto Internet -> LAN Network and change the values like the following:
- IP Address: 192.168.178.50
- Subnet Mask: 255.255.255.0
- DHCP Type: Server
- Start IP Address: 192.168.178.51
- End IP Address: 192.168.178.254

After that the ip address of the device is changed to **192.168.178.50** all the wifi devices get IP addresses from the accessible network 192.168.178.x and your problem should be solved. Works for me.

**Comment by billsbro** [comment]
Thanks a lot again for your effort. This aint working for me, the device doesnt save the made changes after clicking apply but keeps coming up with its default settings. I dont think its wise to run two dhcp servers in the same scope anyway, but I could work around that by using a split scope.

You can close this thread since this has nothing to do with your software. 

What a piece of junk really, with its hidden config pages and all that. You get what you pay for I guess.

**Comment by masmu** [comment]
You are right. 2 DHCP servers is not a good idea. So disabling the one from the _Hamesound Router_ should work. But I have no idea why it does not save your settings.

It clearly not the best device ... but it made me smile several times :smile:

**Comment by billsbro** [comment]
rebooted both the device and the laptop and tried again, it now saves the settings

but the sound still drops when a new song starts :( never mind though I will buy something else some day

**Comment by masmu** [comment]
Are you using _KDE_ or _Amarok_?

**Comment by billsbro** [comment]
gmusicbrowser

**Comment by masmu** [comment]
So, the topic of the issue is "HAME soundrouter discovery issue". Somehow i understood that this is solved now. But you are having issues with the sound being dropped after each track? Correct?
If thats so, 

`pulseaudio-dlna --debug 2>&1 | tee -a debug.log`

will write a debug.log to the current directory.

Please upload / paste it somewhere (e.g. http://pastebin.com/) and paste the link here.
Another guy has the [same issue](https://github.com/masmu/pulseaudio-dlna/issues/61) and there is a fix for that.

**Comment by masmu** [comment]
I could completely reproduce this bug with _gmusicbrowser_. There will be a fix for it in _0.4.4_.

**Comment by masmu** [comment]
* __0.4.4__ - (_2015-08-07_)
    - Added `--disable-ssdp-listener` option
    - Fixed a bug with applications which remove and re-add streams all the time
    - Added a missing dependency `python-psutil`

Since your device uses no standard HTTP 1.0 implementation, you will have to use:
`pulseaudio-dlna --fake-http10-content-length`

But it should work, tested with _gmusicbrowser_.

**Comment by billsbro** [comment]
sorry for messing up the topic in this thread. Network discovery is resolved indeed (but the device is still unstable when I change network settings, the paperclip reboot was needed three time today trying to disable its DHCP server).

The good news is though, I didnt toss the device out of the window and the stream continues playing!

So thanks again.
