### ISSUE TITLE
gapless

### ISSUE THREAD

**Issue by nobanzai** [masmu/pulseaudio-dlna#51]
Hi,
is it possible to have gapless playback with pulseaudio-dlna?
If I don't get gapless playback, is it the application or is it pulseaudio or is it pulseaudio-dlna?
Renderer is my Linn MajiK-DSM, which definitely is capable of gapless playback.

TIA.
Bye.
Michael.

**Comment by masmu** [comment]
Normally this problem is a mix of network performance and selected encoder.
Each encoder uses a certain bandwidth. E.g. the _WAV_ encoder uses much more bandwidth if you compare it to _OGG_ or _MP3_.

So, if you are using wifi with a bad performance and the WAV encoder, it is possible that there are gaps during playback, because your network is not able to send all the data in time.
If you cannot increase your network performance switch to an encoder which uses less bandwidth. So, e.g.: _MP3_. In the current development version you can also lower the _bitrate_ of certain encoders, in case your network is not able to stream 192 kbit/s.

Note: The following depends on the DLNA implementation of your device, but in general you can say:
The higher to quality you are using (a high _bitrate_ and / or an encoder which needs naturally more bandwidth) the lower is the delay and vice versa.

**Comment by nobanzai** [comment]
Oops, obviously my description was misleading. I didn't mean distortet or stuttering sound. What I was referring to, was to have no artificial gaps between songs for example when streaming live concerts.

Bye.
Michael.

**Comment by masmu** [comment]
_pulseaudio-dlna_ basically just sends the audio stream to another device rather than playing it on your local computer. It does not modify the audio stream at all.

So, it all depends on the application which generates the audio stream. For example i am using the official _spotify_ linux client and there is an option in the settings for "gapless playback".

I don't know what you are using, perhaps _totem_, _amarok_ or _rhythmbox_ ... but the place to look for that option is in the application itself.

**Comment by nobanzai** [comment]
Ok, that perfectly answers my question.
I use amarok and it is supposed to be able to playback gapless, but somehow it doesn't work. I go and ask the amarok people.
Thx a lot!
