### ISSUE TITLE
Distortion on multiples sources

### ISSUE THREAD

**Issue by iBigQ** [masmu/pulseaudio-dlna#54]
Hey,
thanks for this extension, works perfectly for me in general!

However, I am observing a problem I cannot explain. Assume I choose the dlna device as default sound device. When I start streaming music, delay is fine at about 2 seconds. The problem occurs if a *new* local sound source starts (i.e. new Playback in PulseAudio Volume Control). This is e.g. when a new sound application starts or each time skype pops up a notification, each time you switch to another desktop.... This also occurs if I change the volume (either application or sound device). At this time, there is distortion created in the stream, that I hear after about 2 seconds.

I want to describe what I mean by distortion. I would expect the two sources to be mixed and to be sent onto the stream. But this has two side-effects:
1) The music playback at this time is not seamlessly but sounds like some scratching because of empty buffers (stuttering) for a bit less than a second.
2) Additionally, (because of the stuttering?) it makes the complete playback to become more delayed

For me, this does not really seem to be a core problem of your pulseaudio-dlna. Instead, it seems to be related to pulseaudio that mixes in the *new* sound. However, if I playback on a local device everything sounds seamlessly. Could there be a problem on the interface between pulseaudio and the dlna playback device?

Btw, if I feed the stream directly from the music application only, there is no stuttering when another sound is played on a local device or when I change the volume.

Are you aware of this or can you even verify this behaviour?
Thanks,

Steffen

**Comment by arahayrabedian** [comment]
I observe Stuttering similar to Steffen's case but when changing volume, not in the mixing between different apps (I feel the 'empty buffers' speaks well here). Not a deal breaker for me though (I change volume from the renderer instead), what's been built here is awesome.

**Comment by masmu** [comment]
Are you guys both using version _0.3.4_? I guess so.

Which encoder are you using? The default one?

To be honest i am not that familiar with that behaviour of the application anymore. I experienced the problems you described myself some time ago. But since i am using the actual development version, it seems as most of those problems are solved there. :pray: 

One problem still persists:
Imaging you have chosen the DLNA device as default sound device and there is currently no active audio stream. When there is a very short sound, such as the skype notification, _pulseaudio-dlna_ advises the DLNA device to play the stream and after playing it, it advises the device to stop playing the stream. Because of the playback delay it might be, that you hear the first part of the sound, but not the rest of it, because despite your device received all the data to play the whole sound, it was advised to stop before it could play all of it.

**Comment by iBigQ** [comment]
Hey,

I am using version 0.3.5 as the latest available version in the repository. Yes, I use the default encoder (which one is default?). I can try with different encoder if you suspect the problem there.

Do you have a separate branch for the development version you are referring to or is it the latest master branch version?

Anyway, nice to hear you already solved it :). You will get to solve the remaining problem as well, I am sure (although I have no advice for you) ;)

**Comment by masmu** [comment]
Oh yeah, you are right. _0.3.5_ is currently the latest one.

The default encoder is _lame_ (so _mp3_). But _lame_ handles changes in volume pretty good. In case you would have used the _wav_ encoder, i would have suggested to try _mp3_.
Anyway, you can give the _wav_ encoder (also the others) a shot, if you want to ...

The latest development version can be found in the [refactor/streaming-server branch](https://github.com/masmu/pulseaudio-dlna/tree/refactor/streaming-server).
But since that version is not packaged, i recommend you to test it just if you know what you are doing.

**Comment by masmu** [comment]
* __0.4.0__ - (_2015-07-27_)
    - Added the ```--fake-http10-content-length``` option
    - The application can now run as root
    - Catch pulseaudio exceptions for streams, sinks and modules when those are gone
    - Fixed a bug where a missing ssdp header field made the application crash
    - New devices are added now during runtime (thanks to [coder-hugo](https://github.com/coder-hugo))
    - Rewrite of the streaming server
    - Upnp devices can now request their audio format based on their capabilities
    - Added AAC encoder
    - If a device stops playing, the streams currently playing on
      the corresponding sink are switched back to the default sink
    - If a device failes to start playing, streams currently playing on
      the corresponding sink are switched back to the default sink
    - Added Chromecast support (new dependency: `python-protobuf`)
    - Fixed a bug where the application crashed when there was no suitable encoder found
    - Added the ```--bit-rate``` option
    - Added additional headers for DLNA devices
    - Added switch back mode also for sinks, not just for streams (new dependency: `python-notify2`)
    - Added better logging
    - Validate encoders for installed dependencies

**Comment by masmu** [comment]
Closed due to inactivity.
