### ISSUE TITLE
pulseaudio-dlna 0.4.1 stopped working

### ISSUE THREAD

**Issue by petereckhardt** [masmu/pulseaudio-dlna#60]
Hello,

thanks a lot for this lovely app. 

The old version (0.3.x) worked very nicely between ubuntu and kodi. Since i accidentially installed 0.4.1 the connection to the dlna renderer is closed some seconds after i do switch to the renderer.

07-30 12:13:05 pulseaudio_dlna.streamserver                   INFO     Requested streaming URL was: /musicbuero_dlna.wav (HTTP/1.1)
07-30 12:13:05 pulseaudio_dlna.streamserver                   INFO     Got request from 192.168.123.132 - GET /musicbuero_dlna.wav HTTP/1.1,200,-
07-30 12:13:05 pulseaudio_dlna.streamserver                   INFO     Client 192.168.123.132 registered to stream /musicbuero_dlna.wav.
07-30 12:13:05 pulseaudio_dlna.streamserver                   INFO     Processes of /musicbuero_dlna.wav initialized ...
sox WARN wav: Length in output .wav header will be wrong since can't seek to fix it
07-30 12:13:05 pulseaudio_dlna.streamserver                   INFO     Requested streaming URL was: /musicbuero_dlna.wav (HTTP/1.1)
07-30 12:13:05 pulseaudio_dlna.streamserver                   INFO     Client 192.168.123.132 unregistered stream /musicbuero_dlna.wav using method 2.
07-30 12:13:05 pulseaudio_dlna.streamserver                   INFO     Got request from 192.168.123.132 - GET /musicbuero_dlna.wav HTTP/1.1,200,-
07-30 12:13:05 pulseaudio_dlna.streamserver                   INFO     Client 192.168.123.132 registered to stream /musicbuero_dlna.wav.
07-30 12:13:12 pulseaudio_dlna.streamserver                   INFO     Client 192.168.123.132 unregistered stream /musicbuero_dlna.wav using method 2.
07-30 12:13:14 pulseaudio_dlna.streamserver                   INFO     Stream closed. Cleaning up remaining processes ...
07-30 12:13:14 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink1"
07-30 12:13:15 pulseaudio_dlna.pulseaudio                     INFO     The device "MusicBuero (DLNA)" was stopped.
C07-30 12:13:34 pulseaudio_dlna.pulseaudio                     INFO     Remove "musicbuero_dlna" sink ...
Application is shutting down.
07-30 12:13:34 pulseaudio_dlna.pulseaudio                     INFO     Remove "musicbuero_dlna" sink ...
07-30 12:13:34 pulseaudio_dlna.pulseaudio                     ERROR    Could not remove entity 43

Just for your info. Old version still works very nicely.

**Comment by masmu** [comment]
I guess this is because of the codec. In 0.4.x _pulseaudio-dlna_ chooses the codec depending on the devices capabilities and a priority list of available encoders. At the moment _wav_ has the highest priority and is therefore chosen over _mp3__ and others.

Could you check this by starting it with another encoder?
```pulseaudio-dlna --encoder mp3``` or
```pulseaudio-dlna --encoder opus```

**Comment by petereckhardt** [comment]
Hello Massimo,

that was a fast reply :-)

You are right using -e mp3 works nicely. In 3.5.1 - e wav did work also.

Anyway a great program.  Makes streaming with pulse audio so much easier.

Take care and thanks a lot for the quick help.

Peter



engrea GmbH
Im Unterfeld 39
76297 Stutensee



Am 30. Juli 2015 12:41:36 schrieb Massimo Mund <notifications@github.com>:

**Comment by masmu** [comment]
I did not modify the _wav_ encoder. Which version of _kodi_ are you using?

**Comment by iBigQ** [comment]
Same problem here, just updated to the new version in the repository, Kodi was not modified. I also got the 
*sox WARN wav: Length in output .wav header will be wrong since can't seek to fix it*
message. I started pulseaudio-dlna without any parameters. I will also try with the mp3 encoder

**Comment by petereckhardt** [comment]
Hello Massimo,

Kodi Version is 15. I tried to use flac.  That works also.  Seems problem 
only appears with wav.

Greetings
Peter

engrea GmbH
Im Unterfeld 39
76297 Stutensee



Am 30. Juli 2015 15:55:27 schrieb Massimo Mund <notifications@github.com>:

**Comment by masmu** [comment]
@petereckhardt 
Thanks for your testings. Those were indeed very helpful :+1: 

I could track the problem down. Its a mix of my performance optimizations and _kodi_'s way of detecting audio formats.
But currently i am not quite sure whats the best way to solve it.

In the meantime, please just use another encoder.

**Comment by petereckhardt** [comment]
Hello Massimo,

i can nicely live with flac.  No problem.

Have a great weekend

Peter

engrea GmbH
Im Unterfeld 39
76297 Stutensee



Am 31. Juli 2015 12:29:16 schrieb Massimo Mund <notifications@github.com>:

**Comment by masmu** [comment]
* __0.4.2__ - (_2015-08-02_)
    - The mp3 encoder is now prioritize over wav
    - Added '--disable-switchback' option
    - Wav encoders do not longer share their encoder process

**Comment by rog4l** [comment]
Hello,

I am receiving same error with the wav encoder and just wanted to ask if there is any chance for fix of that? 
The encoder option set to mp3 work perfectly fine, but as an mp3 is a lossy compression doesn't that have an influence on the sound quality?
Also as it is mentioned in the documentation, the usage of wav encoder should cause a shorter delay in  playback. In my case the delay is around 5-7 seconds for mp3.
Below are some couple lines from the log before the error occurs. After that stream gets closed and the DLNA renderer gets disconnected.
Installed version is 0.4.7

12-28 23:26:53 pulseaudio_dlna.streamserver                   INFO     Client 192.168.1.2 registered to stream /dWRuPSJ1dWlkOjNiZjAxNzdhLWVmZGUtZDVmMi1mMDA1LTAxOTk1MjAxNTdGIix0eXBlPSJicmlkZ2Ui/stream.wav.
12-28 23:26:53 pulseaudio_dlna.streamserver                   DEBUG    Starting processes "parec --format=s16le -d airtrymr_dlna.monitor | sox -t raw -b 16 -e signed -c 2 -r 44100 - -t wav -b 16 -e signed -c 2 -r 44100 -L -"
12-28 23:26:53 pulseaudio_dlna.streamserver                   INFO     Processes of /dWRuPSJ1dWlkOjNiZjAxNzdhLWVmZGUtZDVmMi1mMDA1LTAxOTk1MjAxNTdGIix0eXBlPSJicmlkZ2Ui/stream.wav initialized ...
sox WARN wav: Length in output .wav header will be wrong since can't seek to fix it
