### ISSUE TITLE
Veetop AirMusic box

### ISSUE THREAD

**Issue by polyphant1** [masmu/pulseaudio-dlna#64]
This was working perfectly with my [AirMusic box](http://www.amazon.co.uk/Veetop%C2%AE-HiFi-AirMusic-Box-Streaming/dp/B00JKD09B8) up until commit 
15e51f1914f5321c9758aa5a20898522a149a2ea

Since then it is not recognised at all. My Chromecast is recognised. There have been some pretty major changes since then, not sure what's broken it for me. I'm on Ubuntu Gnome 15.04.

Thanks

**Comment by masmu** [comment]
It is not being recognized? Thats odd ... The discovery of the devices is pretty solid.
Can you retry it a few times? And if that does not work, try to power your device on while _pulseaudio-dlna_ is running.

**Comment by masmu** [comment]
* __0.4.4__ - (_2015-08-07_)
    - Added `--disable-ssdp-listener` option
    - Fixed a bug with applications which remove and re-add streams all the time
    - Added a missing dependency `python-psutil`

**Comment by polyphant1** [comment]
Just tried a couple more times this evening on the latest version (0.4.4) with no luck, even powering on whilst _pulseaudio-dlna_ is running.  Any debug output I can provide?

**Comment by polyphant1** [comment]
FYI 15e51f1914f5321c9758aa5a20898522a149a2ea is still working. Start up output:

```
python pulseaudio_dlna/
Using localhost: 192.168.1.5:8080
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.2
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.2
INFO:root:Discovery complete.
INFO:root:Found devices:
<CoinedUpnpMediaRenderer name="AirMusicBox" short_name="airmusicbox" state="idle">
INFO:root:You can now use your upnp devices!
INFO:root:PulseWatcher.on_device_updated "/org/pulseaudio/core1/sink11"
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.2
INFO:root:"AirMusicBox" registered.
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.2
192.168.1.2 - - [07/Aug/2015 23:32:14] "GET /airmusicbox.stream HTTP/1.1" 200 -
INFO:root:starting sending stream to "AirMusicBox"
INFO:root:"AirMusicBox" is playing.
INFO:root:PulseWatcher.on_device_updated "/org/pulseaudio/core1/sink11"
INFO:root:PulseWatcher.on_device_updated "/org/pulseaudio/core1/sink11"
```

**Comment by masmu** [comment]
I made a [branch](https://github.com/masmu/pulseaudio-dlna/tree/bug/reliable-discovery) for testing purposes.

Could you check it out and provide a _debug.log_?

1) Make sure you installed the dependencies (if you installed _0.4.4_ you should have installed them)

Otherwise:
`sudo apt-get install python2.7 python-pip python-setuptools python-dbus python-beautifulsoup python-docopt python-requests python-setproctitle python-gobject python-protobuf python-notify2 python-psutil vorbis-tools sox lame flac faac opus-tools`

2) Install _virtualenv_ & _python-dev_

All Ubuntu versions prior to 14.10 Utopic need to install:
`sudo apt-get install python-virtualenv python-dev`

All Ubuntu versions above install:
`sudo apt-get install virtualenv python-dev`

3) Checkout the code, run it and write a _debug.log_.
```
git clone https://github.com/masmu/pulseaudio-dlna.git
cd pulseaudio_dlna/
git checkout bug/reliable-discovery
make
bin/pulseaudio-dlna --debug 2>&1 | tee -a debug.log
```

**Comment by polyphant1** [comment]
Apologies for the delay in trying this. Ran through the instructions today ... and it now works. Air Music Box picked up fine, and audio streams to it. 

This is only the case for this branch, */bug/reliable-discovery*,  run through a Python virtual-env. Global install fails on startup,
```
$ pulseaudio-dlna 
bash: /usr/bin/pulseaudio-dlna: No such file or directory
```
and the PPA version still fails to identify.

Here's [a gist](https://gist.github.com/polyphant1/9a9518e77570a6f0a9ae) with the logs captured on the succesful branch through the virtual-env

**Comment by masmu** [comment]
Yeah. You are right. The branch was just for testing the actual changes i made for this to work. Now it has reported twice to be working you will find these in the next release.

Did you do a `sudo make install`? That could have messed up your global installation. In general: Try to avoid `sudo make install` commands whenever its possible.
Since you are using _Ubuntu_ you have a package manager for that.

**Comment by polyphant1** [comment]
Thanks for the tip, and the very speedy changes
