### ISSUE TITLE
No connection to Onkyo reciever with ValueError.

### ISSUE THREAD

**Issue by CerebrosuS** [masmu/pulseaudio-dlna#72]
Hey,

I tried to connect to an Onkyo TXNR509 reciever and get to following traceback.

http://cxg.de/_d53b5e.htm

System: Uptodate Archlinux, Kernel 4.1.5-1-ARCH
Build: aur-build

Thx for your help. :-)

**Comment by CerebrosuS** [comment]
Hey,

I got more debug information and could get the renderer url which is: http://2.2.2.102:8888/upnp_descriptor_0 .

Now I tried to connect the url given and got a different error message which following statement:

08-20 12:45:14 pulseaudio_dlna.plugins.chromecast.renderer    INFO     The Chromecast seems not to be an original Chromecast! Model name: "TX-NR509" Skipping device ...

Maybe this is helpful for finding the error.

Thx.

**Comment by masmu** [comment]
Hi,

The first bug is fixed in the [bug/mimetype-lookup](https://github.com/masmu/pulseaudio-dlna/tree/bug/mimetype-lookup) branch. Could you try it?

The second error is a weird one.
Could you provide a full _debug.log_?

I have no idea of Arch Linux, but for the following in _Ubuntu_ you need the package `python-dev` and the `virtualenv` binary installed.

```bash
git clone https://github.com/masmu/pulseaudio-dlna.git
cd pulseaudio-dlna/
git checkout bug/mimetype-lookup
make
bin/pulseaudio-dlna --debug 2>&1 | tee -a debug.log
```

**Comment by CerebrosuS** [comment]
Worked like a charm with the mimetype-lookup branch. Will this branch be merged to master in future?

Thx.

**Comment by masmu** [comment]
Sure, this will be in _0.4.5_.

You are welcome!
