### ISSUE TITLE
Some devices (M$?) on the network cause discovery to crash

### ISSUE THREAD

**Issue by Cygn** [masmu/pulseaudio-dlna#96]
File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/plugins/upnp/renderer.py", line 239, in get_protocol_info
    url = self.service_connection.control_url
AttributeError: 'NoneType' object has no attribute 'control_url'

This is when running in a medium sized network (~200 boxes)  with mixed OSs.
Complete --debug here: 
http://paste.fedoraproject.org/273581/44370475

**Comment by masmu** [comment]
Hey, could you try out that [branch](https://github.com/masmu/pulseaudio-dlna/tree/bug/no-control-url)? It should ignore those devices and therefore fix the crash.

**Comment by Cygn** [comment]
yep, that makes it:
10-01 16:24:55 pulseaudio_dlna.plugins.upnp.renderer          INFO     The device "UPMC-PC (DLNA)" does not specify a service transport url. Device skipped!
10-01 16:24:56 pulseaudio_dlna.plugins.upnp.renderer          INFO     The device "UPMC-PC (DLNA)" does not specify a service transport url. Device skipped!

however, I've got this immediately after:
10-01 16:25:03 pulseaudio_dlna.pulseaudio                     ERROR    PulseAudio seems not to be running or PulseAudio dbus module could not be loaded.

I don't know if it's related. pulse runs ok and dbus module is loaded. 
Note that I run from dev directory after 'make'. It is not installed systemwide.

**Comment by masmu** [comment]
I am pretty sure this is not related. 

That it is not installed system wide should be fine. If you want to ensure that, uninstall the system wide installation and try out the local copy again.

In general _pulseaudio_'s dbus module is not the stables pieces of software. Someone told me in _pulseaudio_ 6.0 it is not even officially supported, cause it can make _pulseaudio_ crash. If you have the option consider a restart of the computer _pulseaudio_ is running on. Just to make sure this is a one timer. I've experienced problems with that too. But those were gone after a restart and since quite some time I have no problems with that any more ...
